### PR TITLE
measure Internet speed (module: internetspeed)

### PR DESCRIPTION
**Pull request by sanderjo**
for the time being, based on thinkbroadband.com provided files

### CODE REVIEW

**Comment by jeffgeorge** [comment]
@sanderjo -- Have you considered seeing if we can base this functionality on https://github.com/sivel/speedtest-cli ? They're a python project dedicated to doing speedtests based on speedtest.net, which has global providers, rather than being UK-centric.

**Comment by sanderjo** [comment]
Hi @jeffgeorge 

Yes, I've considered that. I've even created my own module talking to fast.com ; see https://github.com/sanderjo/fast.com . Works beautifully.

However, @Safihre didn't like if because of scraping. And of course the provider speedtest or fast.com can decide to block it at any moment. :-(

So therefore I've chosen the way of downloading a plain file. Next step is to host those files on sabnzbd.org / github, so that we're fully in control.

**Comment by jeffgeorge** [comment]
Carry on, then! Once they're on sabnzbd.org they'll be served up by Cloudflare's CDN network, so it should be a reasonable globally-distributed means of checking throughput speeds.

**Comment by sanderjo** [comment]
Example output on a slow Wifi-link:  `5 MB/s  (40 Mbps)`
image



Example output on a GigE-link: `81.7 MB/s  (653.6 Mbps)`

image

**Comment by Safihre** [comment]
Replaced it with 3 (5MB/10MB/20MB) files hosted at sabnzbd.org. The speed I get here at my work is higher with smaller files (70MB/s) than when the larger files are also included (55MB/s).
```
git fetch
git reset --hard origin/feature/py3/speedtest
```

**Comment by sanderjo** [comment]
Note to self and @Safihre 

Before starting the test-download, I want to invoke `sabnzbd.downloader.Downloader.do.pause()` so that usenet downloads are not eating bandwidth.

And a `sabnzbd.downloader.Downloader.do.resume()` after that?

As soon as the branch is in py3, I'll send the PR.

**Comment by Hellowlol** [comment]
Why isnt logging used instead of print statements?

**Comment by sanderjo** [comment]
Because with print() you can use the code as a stand-alone program.

**Comment by Safihre** [comment]
@Hellowlol agreed, changed https://github.com/sabnzbd/sabnzbd/commit/d9c42ce6ed1452bfafdcc7fb6c313f8ff2383f9b

**Comment by sanderjo** [comment]
Ah, nice: with one extra manual line in __main__, I get my STDOUT / STDERR logging back
```
if __name__ == "__main__":
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
```
gives output

```
$ ./internetspeed.py
Starting speed test:
DEBUG:root:Basic measurement, with small download:
DEBUG:root:URL is https://sabnzbd.org/tests/internetspeed/5MB.bin
DEBUG:root:Downloaded bytes: 5242880
DEBUG:root:Speed in MB/s: 12.09
DEBUG:root:https://sabnzbd.org/tests/internetspeed/20MB.bin
DEBUG:root:URL is https://sabnzbd.org/tests/internetspeed/20MB.bin
DEBUG:root:Downloaded bytes: 20971520
DEBUG:root:Speed in MB/s: 75.71
Speed in MB/s: 75.71
Speed in Mbps: 609.47
```
Good. Much better than the print.

**Pull request merged**
