### PR TITLE
Client ip logging on first occurence, and later occurences after a minimum of an hour

### PR DESCRIPTION
**Pull request by sanderjo**
I have SAB logging always on +Debug. To avoid API logging to fill out the logging, I turn off api_logging.

The result & problem is that I never see what accesses my SAB instances/

This PR logs the first occurrence from an IP address. Plus a next one from that IP address ... after at least one hour.

@Safihre feedback on:
* the global, non-class variable in config.py: OK?
* wording of the logging
* maybe put the python logging command (occurs 3 times) in a function?

### CODE REVIEW

**Comment by sanderjo** [comment]
Example of logging:

```
$ cat .sabnzbd/logs/sabnzbd.log | grep -i -e Request -e "Starting sabnzbd" | grep -A10000 2023-11-15 | sed -e 's/xxxx:/bdef:/g'  | cut -c-140

2023-11-15 21:21:50,530::INFO::[SABnzbd:1459] Starting SABnzbd.py-4.2.0Alpha2
2023-11-15 21:21:50,667::DEBUG::[interface:169] First time IP: Request GET / from ::ffff:127.0.0.1 [Mozilla/5.0 (X11; Linux x86_64) AppleWeb
2023-11-15 21:21:51,341::DEBUG::[interface:169] First time IP: Request GET /description.xml from ::ffff:192.168.178.41 [DAFUPnP] {}
2023-11-15 21:21:52,178::DEBUG::[interface:169] First time IP: Request GET /api from ::1 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
2023-11-15 21:25:21,375::DEBUG::[interface:169] First time IP: Request GET / from 2001:bdef:b0b:4200:502b:f9f2:12d1:738a [Mozilla/5.0 (X11; 
2023-11-15 21:25:36,254::DEBUG::[interface:169] First time IP: Request GET / from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64) App
2023-11-15 22:21:51,178::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:127.0.0.1 [Mozilla/5.0 (X11; Linux x86_64) App
2023-11-15 22:21:53,179::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::1 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.
2023-11-15 22:25:22,195::DEBUG::[interface:159] Earlier seen IP: Request GET /api from 2001:bdef:b0b:4200:502b:f9f2:12d1:738a [Mozilla/5.0 (
2023-11-15 22:25:36,387::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-15 23:21:52,191::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:127.0.0.1 [Mozilla/5.0 (X11; Linux x86_64) App
2023-11-15 23:21:54,186::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::1 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.
2023-11-15 23:25:22,218::DEBUG::[interface:159] Earlier seen IP: Request GET /api from 2001:bdef:b0b:4200:502b:f9f2:12d1:738a [Mozilla/5.0 (
2023-11-15 23:25:36,850::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 00:21:52,193::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:127.0.0.1 [Mozilla/5.0 (X11; Linux x86_64) App
2023-11-16 00:21:54,191::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::1 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.
2023-11-16 00:25:37,716::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 01:25:38,533::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 02:25:38,937::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 03:25:39,750::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 04:25:40,375::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 05:25:41,229::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 06:25:41,769::DEBUG::[interface:159] Earlier seen IP: Request GET /api from ::ffff:192.168.178.43 [Mozilla/5.0 (X11; Linux x86_64
2023-11-16 06:43:46,055::DEBUG::[interface:159] Earlier seen IP: Request GET / from ::ffff:127.0.0.1 [Mozilla/5.0 (X11; Linux x86_64) AppleW
2023-11-16 06:43:48,182::DEBUG::[interface:159] Earlier seen IP: Request GET / from ::1 [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 
2023-11-16 06:43:51,785::DEBUG::[interface:159] Earlier seen IP: Request GET / from 2001:bdef:b0b:4200:502b:f9f2:12d1:738a [Mozilla/5.0 (X11

```

**Comment by Safihre** [comment]
I don't really see the point.. 
You can also just start SABnzbd with `-w` and all HTTP requests will be logged to `cherrypy.log` in case you ever need them.

**Comment by sanderjo** [comment]
> I don't really see the point.. You either want DEBUG or you don't, can't have it both ways in my opinion.

I wan't DEBUG about what SAB is doing, not all the web interface interactions (each second)

> You can also just start SABnzbd with `-w` and all HTTP requests will be logged to `cherrypy.log` in case you ever need them.

I tried with `-w` and api_logging off, and: cherrypy.log get filled (good), but also stdout and sabnzbd.log are full of API logging. So `-w` overrules `api_logging = 0` ? Is that a bug, or a feature?

**Comment by Safihre** [comment]
That indeed was a bug, fixed.

**Comment by sanderjo** [comment]
Cool. Thanks.

**Pull request closed without merging**
