### PR TITLE
Add releases tag

### PR DESCRIPTION
**Pull request by francoism90**
This seems to be the only thing missing for Flatpak.

I believe this can be automated, but I haven't found a GitHub hook yet.

Thanks

### CODE REVIEW

**Comment by thezoggy** [comment]
Shouldn't this be directed towards master not dev?

**Comment by francoism90** [comment]
@thezoggy I just remember this does not work, you need to include the upcoming version as well.
Maybe this should wait for the next SABnzbd release? As Flatpak will download the latest tar and checks appdata, which is now empty at the moment and already tagged as 3.7.2.

Sorry for the noise, I didn't know the <releases> tag was required for Flatpak.

**Comment by Safihre** [comment]
You will update this every release?

**Comment by francoism90** [comment]
Bit disappointed this hasn't been merged for the 4.0.0 release.

**Comment by Safihre** [comment]
You didn't answer my question about who is responsible for updating this..

**Comment by francoism90** [comment]
I already stated I would gladly maintain the SABnzbd Flatpak. This would indeed be a manual step, however maybe it can be automated as well, since you are already seem to be bumping versions.

This would be the final showstopper of getting this upstream. Flatpak has been getting more attention and most distributions are using it, so it would benefit your project as well.

Not saying it's a must, but not everybody runs Snap for example.

**Comment by Safihre** [comment]
Can you put the right release date? Then I'll merge. Do you also need this in master?

You can take a look at the build script how we could incorporate automatically adding new versions. Should be possible with some extra logic steps.

**Comment by francoism90** [comment]
@Safihre I can correct the date, but it doesn't make much difference. The release/version should be set before creating a new (git) tag.

**Comment by Safihre** [comment]
That doesn't make sense to me. How can we put a release in there that isn't released yet? For example you already put 4.0.0 before it was out. So now we should put 4.0.1 before we even release it?
Seems more logical to do it afterwards when the release is done?

**Comment by francoism90** [comment]
Because Flatpak downloads by commit/tag, so yeah, you should bump your version in appdata before creating the release, otherwise it will use the previous version. In most cases I expect this will be on the same day.

It's the same for Snap right? Or does this work differently?

I don't understand why Flatpak just follows the GitHub release link, but it seems only XML is supported and it should be added to appdata.

**Comment by Safihre** [comment]
Right, so it should be present in the code at the moment the tag is created. That makes more sense.

Snap is a mess 🥲 so not a good comparison.

**Comment by francoism90** [comment]
Yep, sorry if I'm pushing too much btw.

If you could let me know when you're tagging 4.0.1 (or any next release), I would be happy to create a PR for appdata. For now it doesn't matter, since I need to update the current Flatpak for 4.0.0

Thanks.

**Comment by Safihre** [comment]
I added it for 4.0.1, so now you can release it, right?

**Comment by francoism90** [comment]
Let's say you guys release 4.0.1 next month/week, you should add this again to the appdata.xml with the release date of next month/week. Next and final step, is tagging the release, so the Flatpak can point to this tarball (which includes the changelog of appdata.xml).

I don't think you need to include actual changes, the release date seems to be key.

**Pull request merged**
