### PR TITLE
Experimental version for using mypyc to read sockets

### PR DESCRIPTION
**Pull request by puzzledsab**
I've been experimenting with mypyc and it seems like this code may result in increased download speed, both compiled and uncompiled. I think it's better compiled, though.

To compile it, check out the feature/mypyc branch from https://github.com/puzzledsab/sabnzbd.git, go to sabnzbd/sabnzbd and run `mypyc readsock.py`, then run SABnzbd.py as usual. This requires everything you need to run mypyc, and python from command line.

What it does is read multiple blocks of data from the socket in one go, and the module for doing so it what should be compiled.

I don't have a good setup for testing it properly myself so I'd be very interested to hear how it performs for anyone who are currently not able to use the full bandwidth. If git has no complaints then there will be Mac and Windows versions, but they won't be compiled. If anyone want to try to run the compiled version on Windows then I'd be happy to help but it's not for beginners.

And yes, I know it's hacky and it's not actually meant to be merged. It's for testing and discussion.

### CODE REVIEW

**Comment by thezoggy** [comment]
just installed to test out, i only have 1G connection so usually not a problem to get it but there is plenty of times where sab isnt consistent for whatever reason. so curious to see if this makes it more stable

**Comment by puzzledsab** [comment]
It seems like mypyc makes some assumptions if it's compiled inside the sabnzbd dir. Try copying it out of it completely before compiling (cp sabnzbd/sabnzbd/readsock.py .; mypyc readsock.py; cp readsock*.pyd sabnzbd/sabnzbd).

**Comment by thezoggy** [comment]
> It seems like mypyc makes some assumptions if it's compiled inside the sabnzbd dir. Try copying it out of it completely before compiling (cp sabnzbd/sabnzbd/readsock.py .; mypyc readsock.py; cp readsock*.pyd sabnzbd/sabnzbd).

I'm just using the built windows installer and installing it over my existing instance and running from the binary. would you rather me just run from source?

**Comment by sanderjo** [comment]
FWIW:

Building from within ~/git/puzzled_mypyc_sab/sabnzbd gives an error:

```
sander@zwart2204:~/git/puzzled_mypyc_sab/sabnzbd$ mypyc readsock.py
running build_ext
building 'sabnzbd.readsock__mypyc' extension
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sander/.local/lib/python3.10/site-packages/mypyc/lib-rt -Ibuild -I/usr/include/python3.10 -c build/sabnzbd/__native_readsock.c -o build/temp.linux-x86_64-3.10/build/sabnzbd/__native_readsock.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-unused-but-set-variable
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/build/sabnzbd/__native_readsock.o -o build/lib.linux-x86_64-3.10/sabnzbd/readsock__mypyc.cpython-310-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.10/sabnzbd/readsock__mypyc.cpython-310-x86_64-linux-gnu.so -> sabnzbd
error: could not create 'sabnzbd/readsock__mypyc.cpython-310-x86_64-linux-gnu.so': No such file or directory
```

Building from the main directory seems to go OK?

```
sander@zwart2204:~/git/puzzled_mypyc_sab$ mypyc sabnzbd/readsock.py 
running build_ext
building 'sabnzbd.readsock__mypyc' extension
creating build/temp.linux-x86_64-3.10
creating build/temp.linux-x86_64-3.10/build
creating build/temp.linux-x86_64-3.10/build/sabnzbd
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/sander/.local/lib/python3.10/site-packages/mypyc/lib-rt -Ibuild -I/usr/include/python3.10 -c build/sabnzbd/__native_readsock.c -o build/temp.linux-x86_64-3.10/build/sabnzbd/__native_readsock.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-unused-but-set-variable
creating build/lib.linux-x86_64-3.10
creating build/lib.linux-x86_64-3.10/sabnzbd
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/build/sabnzbd/__native_readsock.o -o build/lib.linux-x86_64-3.10/sabnzbd/readsock__mypyc.cpython-310-x86_64-linux-gnu.so
building 'sabnzbd.readsock' extension
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c build/sabnzbd/readsock.c -o build/temp.linux-x86_64-3.10/build/sabnzbd/readsock.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option -Wno-unused-but-set-variable
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/build/sabnzbd/readsock.o -o build/lib.linux-x86_64-3.10/sabnzbd/readsock.cpython-310-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.10/sabnzbd/readsock__mypyc.cpython-310-x86_64-linux-gnu.so -> sabnzbd
copying build/lib.linux-x86_64-3.10/sabnzbd/readsock.cpython-310-x86_64-linux-gnu.so -> sabnzbd
```

**Comment by puzzledsab** [comment]
@thezoggy I have reduced the time it will spend on each connection in the default version. It may work better with a high transfer rate. You'll need to run it from source to try the compiled version.

@sanderjo The compiling is a bit confusing. On Windows it made two different version of the pyd, depending on where I ran it from. One was 10 KB and one was 24 KB. When compiling outside the sabnzbd dir it only made the 24 KB version.

If you like, you can try varying the numbers for timeout (0.00011) and blocks read (16) in readsock.py. It could give different results.

Anyway, thanks for testing. I suspect that it is a combination of special circumstances in my setup and yappi not measuring the time used by the pyd files correctly that makes it look like there is an improvement. I initially didn't think it would make much of a difference when I started because it still has to call the uncompiled Python lib modules so it can't release the GIL.

**Comment by thezoggy** [comment]
Once the speed regression is fixed I'll check this out again.

**Comment by puzzledsab** [comment]
I have included the fix for the speed problem and dropped using mypyc. However, I still think reading multiple blocks from the socket before returning may be a good idea for those who are limited by CPU power so I'm not giving up just yet. It seems like a waste to go through the whole Downloader:run loop again after just 16 KB if there are still data available to be read. I have limited it to 4 blocks (64 KB) in this version. If you run from source you can try a higher number in line 188 in `sabnzbd/newswrapper.py`.

**Pull request closed without merging**
