### PR TITLE
Customized Add-NZB in Glitter, added extra tooltips

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by shypike** [comment]
In Firefox (on Mac) the Add dialog looks odd:
Snapshot

**Comment by Safihre** [comment]
Force-refresh it, probably the cache at work again.

I think I will also add anti-cache to Glitter, but then with the version and build number. This way the cache is kept in between versions and start-up is just that tiny bit faster.

**Comment by shypike** [comment]
The p=$pid trick solved the problem. Please add that fix too.

**Comment by Safihre** [comment]
Yeah you're right! Will use the $pid.
Since both cache and cherrypy have to come from the disk, doesn't seem to have any benefit.

**Comment by Safihre** [comment]
Updated.

**Pull request merged**
