### PR TITLE
Feature: Server stats graphs

### PR DESCRIPTION
**Pull request by Safihre**
image

### CODE REVIEW

**Comment by thezoggy** [comment]
assuming your graph has a little button to show day/month/etc view.. since the totals and whats displayed only match up with 'today' ?

**Comment by Safihre** [comment]
So far I will only support month view because in the BPSmeter I am only saving it per day, not per hour etc.
Up to now we did not record the data per day, so there's no historical data.

**Comment by thezoggy** [comment]
be nice if we showed all the servers in a stacked area graph, 
sab
image is from netdata -- https://my-netdata.io/  (they use dygraph for their graphs -- http://dygraphs.com/)

**Comment by Safihre** [comment]
Let's first start with this 😉

**Pull request merged**
