### PR TITLE
Move IP address determination into a module sabnzbd.utils.getipaddress

### PR DESCRIPTION
**Pull request by sanderjo**
As discussed here: https://github.com/sabnzbd/sabnzbd/issues/212

### CODE REVIEW

**Comment by thezoggy** [comment]
should add if dns is working (internet is reachable)..  and if the internet can reach it..

**Comment by sanderjo** [comment]
Explicit DNS checking? Good point. I'll add that to the Dashboard.

**Comment by thezoggy** [comment]
prob have a list of 3 urls... check each three and only report fail if all 3 are unreachable?
have this check tie in with the ip check.. so it can be disabled/enabled with it.. since they would check the same sites?

**Comment by sanderjo** [comment]
More stuff into the dashboard:
- DNS Check
- Disk speed measuring (only when Refresh is clicked), based on separate module

On startup (no disk speed):
sabnzbd dashboard - on startup

After clicking Refresh:
sabnzbd - dashboard - after refresh

With no network at all:
sabnzbd - dashboard ---- no network

**Comment by shypike** [comment]
Looks good.
Little suggestion. When no network address is found, why not show something like "not found", "cannot be determined", instead of nothing. That way people know that something is wrong.

**Comment by sanderjo** [comment]
Something like this?

sabnzd - dashboard - message if not good

**Comment by sanderjo** [comment]
Or maybe better: only in the template presentation (still None in the python code), and ... colors! Implemented for the Public IPv4 address in the picture below:

sabnzbd - dashboard with colors

The cheetah template code is:

```
        <!--#set $odd = not $odd#-->    <tr class="<!--#if $odd then "odd" else "even"#-->">
               <td>Public IPv4 address</td><td>  
                   <!--#if $publicipv4#-->$publicipv4
                   <!--#else#--><B><font color="red">No public IPv4. That is bad</font></B>
                   <!--#end if#-->
               </td></tr>

```

**Comment by thezoggy** [comment]
prob need to create the relevant translation strings and use them there?

**Comment by shypike** [comment]
Already merged through other pull request.

**Pull request closed without merging**
