### PR TITLE
Switch from pynotify to notify2

### PR DESCRIPTION
**Pull request by jcfp**
For basic notifications it's pretty much a plug-in replacement, so code changes are minimal. Got rid of the warnings handling as that stuff caused problems with dbus.

Noticed and removed some gntp leftovers while at it.

### CODE REVIEW

**Comment by Safihre** [comment]
Just for my basic understanding, what extra `apt-get`'s do I need to do to get it working in my plain Ubuntu? 👷

**Comment by jcfp** [comment]
Installing _python3-notify2_ should do the job on any reasonably modern desktop environment.

**Comment by jcfp** [comment]
Found an issue with my changes, when sab is started as a daemon but shut down from the web interface on the same system. Will look for a fix later and ping you once it's done.

**Comment by jcfp** [comment]
@Safihre ^^ that should do the job.

**Pull request merged**
