### PR TITLE
Get apikey

### PR DESCRIPTION
**Pull request by Hellowlol**
This is a inital pr for https://github.com/sabnzbd/sabnzbd/issues/545

Must be true: Only requests from your localnetwork is allowed

Any of:
List of iprange,
disabled apikey,
blank username and password

if username and password set you you need to supply the ma_username and password or some of the other contions ablemust be true.
If apikey is given it needs to be correct.

I havnt really tought about the security risks so i have no idea if this is the worst idea ever.. :P

### CODE REVIEW

**Comment by thezoggy** [comment]
which apikey? full or nzb? we already provide QR code for apikey's to make it easy to add to mobile..

**Comment by Hellowlol** [comment]
Full key. Yeah and that awesome for mobile, in this case it would be sabnzbd would be automatically discovered on the local network and the thirdparty app would automatically fetch the apikey and be ready for use.

**Comment by Safihre** [comment]
Evaluating your code I realized this exact function is already build-in to SABnzbd for a while and that it is also in the wiki:
http://wiki.sabnzbd.org/api#toc48
http://localhost:8080/sabnzbd/api?mode=config&name=set_apikey

This function will ask for username/password if those are set or for api-key when that one is set.
Also note that SAB will always auto-generate an API-key when it is first started. 
So I wouldn't know for sure how auto-discovery would work, only if that install by default also had ```disable_apikey``` turned on.

**Comment by thezoggy** [comment]
he doesnt want to set an apikey.. which is also bad to do.. especially if the existing apikey is already set and used for other apps. he just wants to mimic apps like emby which listen to a multicast call to return info for discovery.. basically an app sends out a broadcast signature for sab.. and see if something comes back.. if so.. get said data (apikey) and use it. instead of expecting the user to know the sab info/apikey.... personally i think this request is dumb as your asking the user to give the app the username+pw of the sab instance.. which in my mind is much more sensitive than the apikey.. as a lot of time people use the username/pw in other places.. thus if this info is sniffed.. thats far worse than someone learning of the apikey.

**Comment by Hellowlol** [comment]
@thezoggy It only returns the current apikey or generate a new one if it dont exist. The multicast thing already exist in sabnzbd.

**Comment by Safihre** [comment]
Indeed I was mistaken!
@Hellowlol So this would just be in case you know the username and password but not the API key?
Because if you already know the API-key, you know it. And if the user disabled the API-key and has no username/password, you don't need it anyway.

**Comment by Safihre** [comment]
@shypike I don't really see the general use-case for this, so for now we can close it (in my opinion).

**Pull request closed without merging**
