### PR TITLE
Add shortcuts

### LINKED ISSUE #1556: [Feature Request] Add some basic shortcuts/keybindings
I was thinking about something similar to NZBGET, such as Shift+P to pause the current downloads, "A" to add a new nzb etc.

### PR DESCRIPTION
**Pull request by SKBotNL**
This pull request adds the following shortcuts:
A: add nzb
P: pause the queue
S: show the status popup
C: opens the config

A good idea may be to make a config entry to disable and edit the keybinds (which I can try to do later)

This also closes #1556

### CODE REVIEW

**Comment by SKBotNL** [comment]
Seems like some checks failed, don't think it's my code though

**Comment by Safihre** [comment]
@SKBotNL You are right, it's something I broke yesterday.

**Comment by SKBotNL** [comment]
I don't really understand how the config works, so I can't make a toggle myself

**Comment by SKBotNL** [comment]
@Safihre can you make a toggle to disable/enable the shortcuts?

**Comment by SKBotNL** [comment]
@Safihre I forgot to push an addition that makes it that if you press 'S' again it closes the status popup. I will push it now.

**Pull request merged**
