### PR TITLE
Force UnRar and Multipar to output UTF8

### PR DESCRIPTION
**Pull request by Safihre**
It is possible to force UnRar and Multipar to output nice clean UTF8. Now that we are on Python 3, we can actually use that!
We use the output to parse which files were extracted by UnRar so we can keep track of files to sort etc.
However, it is only fully supported on UnRar 5.50+, which is not available for Ubuntu 16.04 LTS version. Ubuntu 16.04 only has the 5 year old version 5.30 😢

To prevent unpacking not working at all, I had to increase the "minimum" required version of UnRar (not really minimum, since it will still work just fine).
With this change users of UnRar 5.30 will get a warning when starting SABnzbd: `Your UNRAR version is 5.30, we recommend version 5.50 or higher`. 
Also, Direct Unpack will not work and Automatic renames will not work when using the SABnzbd option `overwrite_files`.

### CODE REVIEW

**Comment by sanderjo** [comment]
Cool!

**Comment by sanderjo** [comment]
I did a quick test with https://raw.githubusercontent.com/sanderjo/NZBs/master/ASCII-Japanese---utf-in-nzb---made-by-nyuu.nzb

plain git version:
`Renaming "/home/sander/Downloads/incomplete/ASCII-Japanese---utf-in-nzb---made-by-nyuu/HelloWorld-ããã«ã¡ã¯ä¸ç.bin" to "/home/sander/Downloads/incomplete/ASCII-Japanese---utf-in-nzb---made-by-nyuu/HelloWorld-こんにちは世界.bin"`
So: strange chars.

after `git checkout bugfix/unicodeunrar`:

`2020-09-22 18:29:33,586::DEBUG::[newsunpack:2111] Quick-check will rename HelloWorld-ããã«ã¡ã¯ä¸ç.bin to HelloWorld-こんにちは世界.bin`
... so still strange chars. 

Disclaimer: I don't know if the source NZB and my test method are correct.

**Comment by Safihre** [comment]
You should look for the lines that show the output of unrar (or direct unpack) and around there it also shows the Newfiles it detected.

**Comment by Safihre** [comment]
After further contact with the UnRar developer (very friendly guy!), he showed me that we can now can use long-path notation for input and output folders. It also works for unicode input/output.
As such, we no longer need to trim the path on Windows to be maximum 70 characters.
I also tested this with MultiPar.
Additionally, I tested what happens if inside the rar-file there is a folder (with unicode) that we then unpack to a long-path destination from a long-path destination. 
All works 🥳 

```
UNRAR 5.91 x86 freeware      Copyright (c) 1993-2020 Alexander Roshal


Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part01.rar

Creating    \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements  OK
Extracting  \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements\100MB.bin  10%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part02.rar

...         Téléchargements\100MB.bin                                 20%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part03.rar

...         Téléchargements\100MB.bin                                 31%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part04.rar

...         Téléchargements\100MB.bin                                 41%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part05.rar

...         Téléchargements\100MB.bin                                 52%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part06.rar

...         Téléchargements\100MB.bin                                 62%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part07.rar

...         Téléchargements\100MB.bin                                 73%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part08.rar

...         Téléchargements\100MB.bin                                 83%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part09.rar

...         Téléchargements\100MB.bin                                 94%

Extracting from \\?\C:\Users\me\Videos\Complete\Téléchargements\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\Téléchargements.part10.rar

...         Téléchargements\100MB.bin                                 OK 
All OK


Process finished with exit code 0

```

**Comment by sanderjo** [comment]
And no effect from `[SABnzbd:1163] Preferred encoding = cp1252` ? I don't think so, but just checking.

So ... does it work with Chinese chars? A bit rigourous testing than a few accent aigus ...

**Comment by thezoggy** [comment]
The windows codepage 15xx is better than ascii but doesn't do utf. Like in sickbeard days the cp1512 would mangle utf on console but would be handled just fine in code/logs where it was coded just fine. Win10's powershell or windows terminal should handle utf just fine

**Comment by Safihre** [comment]
If I understand correctly, the `getpreferredencoding()` result shows with which charset Python would interact with external processes it starts. That is, unless the external processes decide to output differently, like we now force for UnRar and Multipar.
So on Windows it doesn't really say much..

**Pull request merged**
