### PR TITLE
Simplify delay if no articles were found for a server

### PR DESCRIPTION
**Pull request by Safihre**
@puzzledsab I changed a bit the skipping of servers that have no articles.
What do you think of this version?

### CODE REVIEW

**Comment by puzzledsab** [comment]
Not sure why you `int()` the time but the logic is definitely an improvement.

**Comment by Safihre** [comment]
Did I maybe miss something? Because you specifically implemented `last_busy` and `last_searched`, so did I miss some cases here?

The `int` is because the comparison between float and int is slower. Maybe it's too much of a micro-optimization...

**Comment by puzzledsab** [comment]
My solution distinguished between the time since it last looked for an article and when it was last busy downloading. That way, if there were several levels of backup servers and the articles were trickling down slowly, it wouldn't stop searching too quickly between each new article and make it even slower.

It was an issue because I initially had longer delays between each time it searched when it was idle. Now that it's reduced to 1 second between searches it probably doesn't matter.

I love micro-optimization :) As far as I can tell, both `nw.timeout` and `nzo.avg_stamp` are float, though? `next_article_search` can what you chose. Also, according to my tests with timeit, you need to avoid 5 int/float comparisons to save more than the cost of calling `int()` once.

**Comment by Safihre** [comment]
> I love micro-optimization :) As far as I can tell, both nw.timeout and nzo.avg_stamp are float, though? next_article_search can what you chose. Also, according to my tests with timeit, you need to avoid 5 int/float comparisons to save more than the cost of calling int() once.

Ah, thanks for testing 😁 Then it's not worth it and it can just stay a float.

Have to see why the test are failing though, somehow the `TryList` objects are kept a few seconds longer in memory due to this change. I could just add a `time.sleep(10)` to the tests. But want to make sure there's no bigger underlying issue.

**Comment by puzzledsab** [comment]
Try this:
`if server.next_article_search > now_int and not server.busy_threads:`

Other differences are that my version would continue polling for 1 second after there were no busy_threads and wait 0.5s between each server check instead of 1s in idle mode.

**Comment by Safihre** [comment]
Found the issue to be that the tests didn't auto-disconnect after finishing, so the cleanup of threads would be delayed with 1 second due to the pause.

**Comment by Safihre** [comment]
@puzzledsab Due to your code I finally took the time to look into this whole `read_fds` and `write_fds` stuff.. Looking at the Git Blame much of this code was from before SABnzbd was on Github, so 13+ years old 🤣
I was surprised to see the `read_fds` also contained dormant connections, so I updated the code to remove non-active connections. This way we can use `readkeys` for the improved sleep-timer.

I also found that `write_fds` is useless, because it is only needed if a `socket.connect` is performed in non-blocking mode. However, we only turn on non-blocking-mode _after_ the `socket.connect`. So I removed all of that.

Refactor <3

Let me know if you (or anyone else) spots any flaws in my changes.

**Comment by puzzledsab** [comment]
I never did understand that part of the code. I'm happy to see that it's at least partly because it didn't make sense.

**Pull request merged**
