### PR TITLE
Fix translation tools for python3  (Issue #933)

### PR DESCRIPTION
**Pull request by koppa**
I fixed the translation tools for python3.  This is one step for supporting python3, see issue #933

I added the -n flag to msgfmt back and fixed some encoding problems (bytes objects)

### CODE REVIEW

**Comment by Safihre** [comment]
Nice 👍

**Comment by Safihre** [comment]
Getting some errors though. Maybe I am doing something wrong?
```
PS C:\Users\xxv\Documents\GitHub\sabnzbd> py -3 .\tools\make_mo.py
Email MO files
Compile locale\da\LC_MESSAGES\SABemail.mo

Missing python "C:\Users\xxv\Documents\GitHub\sabnzbd\tools\msgfmt.py". Please install this package first.
PS C:\Users\xxv\Documents\GitHub\sabnzbd> py -3 .\tools\extract_pot.py
Create POT file
python: can't open file 'C:\Program': [Errno 2] No such file or directory
Post-process the POT file
Traceback (most recent call last):
  File ".\tools\extract_pot.py", line 149, in <module>
    src = open('%s/%s.pot.tmp' % (PO_DIR, DOMAIN), 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'po/main/SABnzbd.pot.tmp'
PS C:\Users\xxv\Documents\GitHub\sabnzbd>
```

**Comment by thezoggy** [comment]
why do you open the file in binary mode when the file is text?

**Comment by Safihre** [comment]
Fixed via #1176, but I hope you come back one day to help more on the Python 3 front :)

**Pull request closed without merging**
