### PR TITLE
pre-sanitize filename inside rar file for usage FAT-like filesystems

### PR DESCRIPTION
**Pull request by sanderjo**
Solves https://github.com/sabnzbd/sabnzbd/issues/2165#issuecomment-1113250148

So: sanitize filename inside rar file before unrarring, so that that unrarring is safe on FAT-like systems.

Note: needs `rar` (not `unrar`), for the `rn` (rename) option

### CODE REVIEW

**Comment by sanderjo** [comment]
Example logging (currently very verbose):

```
2022-04-30 15:00:35,327::DEBUG::[newsunpack:530] SJ2: inspecting rar file /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar
2022-04-30 15:00:35,338::DEBUG::[newsunpack:536] SJ2: contents of /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar is 
2022-04-30 15:00:35,339::DEBUG::[newsunpack:538] SJ2: filename is blabla.bin
2022-04-30 15:00:35,339::DEBUG::[newsunpack:538] SJ2: filename is Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt
2022-04-30 15:00:35,340::INFO::[notifier:123] Sending notification: Warning - SJ2: unsafe filename Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt inside rar file /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar (type=warning, job_cat=None)
2022-04-30 15:00:35,340::WARNING::[newsunpack:540] SJ2: unsafe filename Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt inside rar file /media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar
2022-04-30 15:00:35,341::DEBUG::[newsunpack:545] SJ2: rename command is ['/usr/bin/rar', 'rn', '/media/sander/SANDERSTICK/incomplete/reftestnzb__special_chars__545ddc9be613/special_chars.part6.rar', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit \\ blabla \\ dead::beef:0.txt', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit + blabla + dead--beef-0.txt']
```
The last line takes care of the renaming inside the rar.

**Comment by Safihre** [comment]
Oh. This was not what I was expecting. I didn't understand the issue. I thought the `sanitize` functions just needed an extra character to remove. 
This is not something I want to support for such an exotic use case, especially because so much additional steps are needed. 
Don't we already warn users that they are using FAT?

**Comment by sanderjo** [comment]
> This is not something I want to support for such an exotic use case

Fair enough.

> Don't we already warn users that they are using FAT?

Well, only for Complete, and only what the mount / OS is saying.
I then propose: a capability test ("Can I write 'bla :: \ bla.txt' to a directory' ), and then both for Incomplete and Complete.

**Comment by Safihre** [comment]
Sounds like a better idea. We discussed that a number of times already so probably a good idea.
What checks will you do? So we can agree beforehand.

**Comment by Safihre** [comment]
Superseded by #2167

**Pull request closed without merging**
