### PR TITLE
Adding OZnzb to Glitter

### PR DESCRIPTION
**Pull request by Safihre**
Changed OZnzb so it will allow changing of up/down voting.
For out of retention it will only list the users servers, not all of them.
In Glitter you can only give a audio/video score once (just like on the website). Plush allows changing of audio/video rating and shows that change, but it is not actually changed on the website.

untitled

### CODE REVIEW

**Comment by Safihre** [comment]
Minor bug: in IE8 and lower, the 'comment'/'other problem' text-field will not show up when it's selected, because it does not support the new CSS functions.
Will try to make a fix for that later.

**Comment by Safihre** [comment]
Nevermind, just fixed the IE8 bug :)

**Comment by shypike** [comment]
The items in the queue do not show rating info. Is that a concious choice?

**Comment by Safihre** [comment]
Just noticed a small mistake I made for Firefox, fixed that a minute ago!
In Chrome you should see it in the queue? I am testing it on Windows and Ubuntu

**Comment by shypike** [comment]
Great addition. Thank you.
Merged it "squashed", so I have to close the request manually.

**Pull request closed without merging**
