### PR TITLE
Config fixes

### PR DESCRIPTION
**Pull request by Safihre**
Also found a bug that RSS feeds always got disabled when editing the URL.
Might find more things, so maybe keep it open until the next build?

### CODE REVIEW

**Comment by shypike** [comment]
Please give me a sign when you think you're finished.
(I'll build on Wednesday probably).

**Comment by thezoggy** [comment]
bootstrap 3.3.6 is out btw, not sure if you wanna just jump to that

**Comment by Safihre** [comment]
@thezoggy Updated it, but don't think any changes were applicable to us.

**Comment by thezoggy** [comment]
looks like this got pulled early?

**Comment by thezoggy** [comment]
not sure if its by design, but you didnt enable autocomplete on the Categories folder/path field.
the 'Relative folders are based on: ' red is obnoxiously bright.. please revert it back to the dark red that we previously used.

**Comment by Safihre** [comment]
Yes, will change the red.
Still want to change the auto-complete so that it works with relative-paths. Now the auto-complete will put the full path when selecting a value (it already suggest the right relative paths because the API understands it).

**Pull request merged**
