### PR TITLE
correct spelling of 'separate' in various contexts

### PR DESCRIPTION
**Pull request by OneCDOnly**
mnemonic: "_there's **a-rat** in **sep-a-rat-e**._" :D

### CODE REVIEW

**Comment by Safihre** [comment]
You can't do it like this, the translation system automatically updates all the translations and changing texts `skintext.py` would break all the translations since they are mapped to the original text.

Instead you only need to do 1 thing:
Add to `en.po` at the end:
```
msgid "Seperate multiple URLs by a comma"
msgid "Separate multiple URLS with a comma"
```

**Comment by OneCDOnly** [comment]
Ah.... should I go back and try again? ;)

**Comment by Safihre** [comment]
Yeah 😉 changes to translatable texts should always be done via `en.po`

**Comment by OneCDOnly** [comment]
No worries - I knew that bigger-picture stuff would catch me out eventually. I'll try again. The other files only need that word changed in the code comments. Should I re-submit them too?

**Comment by Safihre** [comment]
Sounds good, everything that's not in `T(xxx)` or in `skintext.py` can be corrected directly.

**Comment by OneCDOnly** [comment]
Just thinking about this - as the placeholder text is changed too, the automatic mapping would still work correctly, wouldn't it?

**Comment by Safihre** [comment]
No it's unilateral, we upload the English text to Launchpad and then in a seperate system the translations come back. It only imports the English, not the other languages. Maybe it could, but we didn't set it up like that.

**Comment by OneCDOnly** [comment]
And final question: the format in `en.po` seems to be:
```
msgid "---"
msgstr "---"
```
So, I should therefore append:
```
msgid "Seperate multiple URLs by a comma"
msgstr "Separate multiple URLS with a comma"
```
Correct?

**Comment by Safihre** [comment]
Oops yes indeed that's the correct format, not what I wrote previously!  🙈

**Comment by OneCDOnly** [comment]
No worries, thanks for your patience. :)

**Comment by OneCDOnly** [comment]
Resubmitting as a new pull request so I'll close this one.

**Pull request closed without merging**
