### PR TITLE
Multipar integration for Windows 

### PR DESCRIPTION
**Pull request by Safihre**
I added the Multipar interpreter for Windows (32bit and 64bit), for motivation (speedddd, at least 2x faster repair on my PC) see #420.

Multipar takes things a little different than the other par2-implementations. For example Multipar will first search for all complete files, relatively quickly ("Checking") and only then scan the broken ones ("Verify"). When there are obfuscated file names it will **always** rename the complete ones, but not the in-complete files if it can't repair. So if there are par-blocks missing, you're left with half-renamed set of files after the first repair run.
But that's alll been taken care of, just like joinables! 
The only case I couldn't find any NZB's for were these jobs where the rar-files themselves were then split again. But these are rare nowadays and can be added to the interpreter later. 
I have tested it with many downloads already and so far so good!

I enabled it by default now in the testing phase, with a message to the user. This way enough people will try it and we can get feedback from the users!

### CODE REVIEW

**Comment by thezoggy** [comment]
while i dont think you should squash and rebase everything, see a few commits you could combine.. up to shy though if he cares about the commit noise

**Comment by Safihre** [comment]
Yes, some can be combined indeed. Just to show the steps that were taken to get it working!

**Comment by thezoggy** [comment]
1.2.9.1 came out yesterday btw.. looks like even more performance gains for some :)

https://multipar.eu/changelog
```
This version includes update for some non-popular PCs. It will detect proper cache size for AMD CPU. It will use more cores for Intel Xeon CPU. There would be no difference for most users. But, if someone find a problem, please report it.

Because par2j's "/lc" option was changed, those who use batch script or command-line should be careful. Setting by rate will be more useful than direct number. On MultiPar GUI's option, "CPU usage" slider means number of threads; 1/4, 2/4, 3/4, 4/4, 6/4 of physical cores.
```

**Comment by Safihre** [comment]
@thezoggy interesting!

I have been using this now for a whole as my primary par2 option and I noticed that MultiPar is definitely slower in detecting Obfuscated filenames than par2-tbb is.
However as soon as it finds a file, it immiditaly renames it. So when a second run is done after it fetched more blocks, files are not Obfuscated anymore and it's just as fast.
It also seems to require more disk space during repair than par2-tbb. I use a small caching-SSD of 15GB as my temporary download folder. When a download is 14GB but it needs to repair 12 of 100MB rar's, it wants to reserve 1200MB for it. Because it can't, it will fail with disk-full error while par2-tbb somehow doesn't need all this space beforehand.
But of course the repair is super-fast.

**Comment by shypike** [comment]
Closed?

**Comment by Safihre** [comment]
Have been using this for a while now and works very well for 'normal' jobs, but on these special cases it doesn't behave the same as par2cmdline in those 0.1% of cases. Not the fault of Multipar, but of my interpreter probably. Will re-open when I fix it for all the weird NZB's.

**Comment by thezoggy** [comment]
time to work on this again ?

**Comment by Safihre** [comment]
@thezoggy Although repair performance is amazing with Multipar, verification performance is definitely worse. Not just initial verification, but also the verification after it finished the repair.
The good thing is that with the Prospective Par2 the number of verification-runs will be only 1 in 95% of downloads.
Probably pick this up after finishing the SSL stuff :)

**Comment by mesa57** [comment]
I would like to ask you to pick this up also. 
I have problems with the current par2-tbb, because that only works on win-7 and not on my XP vm.
There are weird kernel.dll dependency's
Multipar however works perfect, so that would be a solution.

Par2 classic (par2cmdline) is not an option, because it cannot process renamed files in a rar set.
It will fail with a 'repair is not possible'. Multipar recognizes that the files should be renamed.

**Comment by Safihre** [comment]
It's on the list, although it was much harder to implement than I originally thought.
Just to be sure: only in 1.1.1 we replaced par2classic by par2cmdline, did you try and see if that makes it better?

**Comment by mesa57** [comment]
Running indeed 1.1.1 and yes, I tried par2cmdline, but it does not work on rar sets with renamed files in it.

**Comment by Safihre** [comment]
Could you send me one of those NZB's to safihre@sabnzbd.org?

**Comment by mesa57** [comment]
Of course :smile: 
Done.

**Comment by Safihre** [comment]
Tested and it seems this is not Par2cmdline's fault, but SAB's!
Working on a fix.

**Comment by Safihre** [comment]
Actually, it is par2cmdline's fault:
The job-folder ends in ```.par2```. this causes par2cmdline not to scan for additional files because it's confused. Even if you specify the paths to each file individually. 
Solution would be to let workdir never end on ```.par2```. 
What do you think @shypike ?

**Comment by Safihre** [comment]
Tested and the job-folder ending on ```.par2``` is also a problem on Ubuntu, so clearly we should fix it.

**Comment by mesa57** [comment]
That will be difficult. 
I could not get hold of par2 tbb to study the difference between the tbb and the normal version.

**Comment by Safihre** [comment]
@mesa57 you should not add NZB files that have par2 in the filename, just remove that before adding. 
I can test both versions on my pc.

**Comment by mesa57** [comment]
Just tested that, and indeed it works :+1:

**Comment by mesa57** [comment]
Funny thing is that par2 tbb has no problem with it (tested with sabnzbd 1.1.0 / x64 / win).

**Comment by Safihre** [comment]
Fixed: https://github.com/sabnzbd/sabnzbd/commit/e70fac98aa4182cccccaf4f1ba997cf18f322b4e

If you have any more NZB's that fail in par2cmdline for different reasons, just send them to me!

**Comment by mesa57** [comment]
Thanks :+1: 
And of course we will if we encounter them :smile:

**Pull request closed without merging**
