### PR TITLE
Fix locale compilation in Python 3

### PR DESCRIPTION
**Pull request by svms1**
This pull request fixes the locale compilation tools for Python 3, a small contribution towards the ongoing effort to make sabnzbd ready for Python 3 (issue #933).

Successfully tested with Python 3.6.5 on Linux with an UTF-8 system locale, so any verification on other operating systems (and locales) would be appreciated.

### CODE REVIEW

**Comment by svms1** [comment]
What were the commands you used? I don't get any errors on Linux even if the paths contain whitespaces.

**Comment by Safihre** [comment]
On Windows it needs to be a list: https://stackoverflow.com/questions/25655173/is-python-subprocess-popen-accept-space-in-path

Maybe you can get that Windows VM 😉 Microsoft offers them: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I tried to do that, but got some other errors that could be due to my local setup.

**Comment by svms1** [comment]
I did change it to use a list exactly for that reason - and because I usually find it more readable than building a string:

    cmd = [TOOL, '-o', mo_file,  fname]
            if extra != '':
                cmd.insert(1, extra)
    ret, output = run(cmd)

Did you run anything else than ```make_mo.py```? I only adapted this and ```msgfmt.py```, but I see ```extract_pot.py``` in your ouput. I didn't change anything in there, so maybe that's the culprit?

If it's not an obvious or straightforward fix I will focus on getting other parts of SABnzbd working on Linux for now since it is the environment I'm most comfortable with. If I make significant progress there I can always circle back and try to fix issues on other platforms.

**Comment by Safihre** [comment]
Makes sense 👍

**Comment by Safihre** [comment]
I pushed the Windows-fix :)

**Pull request merged**
