### PR TITLE
Check busy threads less often if nothing is wrong

### PR DESCRIPTION
**Pull request by puzzledsab**
This part uses 6.25% of the CPU time with just 8 threads according to Yappi, possibly much more with more threads. I think this is a safe and simple way to reduce it significantly.

### CODE REVIEW

**Comment by Safihre** [comment]
Sounds good.
Should we introduce a constant? Maybe it can be the same the same for:
```
server.next_article_search = now + 0.5
```

**Comment by puzzledsab** [comment]
I'm not sure, the use cases are a bit different. `next_article_search` could probably wait several seconds without causing problems, but `next_busy_threads_check` should be delayed less than 1 second for the timeout check. I don't mind either way.

**Comment by Safihre** [comment]
Since timeouts are defined in full seconds, checking every `0.5` should be enough?
Or am I forgetting something?

**Comment by puzzledsab** [comment]
I was a bit worried that `nntp.error_msg` could be set in some magical way I'm not aware of, but if it's not it should be ok.

**Pull request merged**
