### PR TITLE
use native Win-on-ARM64 par2 exe

### PR DESCRIPTION
**Pull request by sanderjo**
closes https://github.com/sabnzbd/sabnzbd/issues/2896

the included par2.exe for Windows-on-ARM64 is from https://github.com/animetosho/par2cmdline-turbo/releases : par2cmdline-turbo-v1.1.1-win-arm64.7z

### CODE REVIEW

**Comment by sanderjo** [comment]
Interesting:

On Windows-ARM64, the native arm64\par2.exe is found

`2024-06-30 11:09:43,982::INFO::[SABnzbd:452] par2 binary... found (C:\Program Files\SABnzbd\win\par2\arm64\par2.exe)
`
... but multipar\par2j64.exe is used / preferred?

`2024-06-30 11:13:44,762::INFO::[misc:1249] [N/A] Running external command: ['C:\\Program Files\\SABnzbd\\win\\multipar\\par2j64.exe', 'r', '-vl2', '-uo', '-vs2', '-vd\\\\?\\C:\\Users\\<USERNAME>\\Downloads\\incomplete\\missing_articles_test_download_100MB\\__ADMIN__', '\\\\?\\C:\\Users\\<USERNAME>\\Downloads`

I guess that is how it works on Windows-X86 too. Is that what we want @Safihre  @animetosho , or prefer par2 from @animetosho ?

**Comment by mnightingale** [comment]
> Having played with this, the major drawback is that the file handling is still using the original par2cmdline which sucks at unicode filenames. Multipar handles that without problems on Windows.

_Originally posted by @Safihre in https://github.com/sabnzbd/sabnzbd/issues/2613#issuecomment-1665630486_
           
I think there is a switch `enable_multipar` you can use to prefer par2cmdline, but it seem it has problems with unicode.

**Comment by Safihre** [comment]
Exactly! It doesn't handle unicode at all on Windows 🥲 so it's just not a good option for regular users.

**Comment by thezoggy** [comment]
I'll just start off saying that I think at some point we prob should do a proper winarm installer/build once there is a enough of a user base and applications to justify it.

From my previous testing I did not see any meaningful value in the arm64 variant par2cmdline-turbo compared to the x64/x86 versions (with regards to speed/being cpu bound):

firefox_2024-06-30_17-52-53

Now I do not have cpu % at the time of my test (as I was mainly focused on time of execution). 
Maybe Sander has better testing that shows another picture though.

**Comment by Safihre** [comment]
Will decline this one until it can handle UTF8 correctly.

**Pull request closed without merging**
