### PR TITLE
Show estimated time left on par2 repair and unrar unpack 

### PR DESCRIPTION
**Pull request by Safihre**
Based on the time spent repairing and unpacking, I figured we can make a rough prediction of the time it will take to finish.

### CODE REVIEW

**Comment by sanderjo** [comment]
image


Nice!!!

**Comment by thezoggy** [comment]
is the format hh:mm? so in sander's image its 24 mins left?

**Comment by Safihre** [comment]
All other times in the GUI are also mm:ss and only hh:mm:ss if mm>60. So it matches the rest and should not be confusing.
Additionally, you see it go down every second so that clears any confusion.. in a second 😅

**Comment by thezoggy** [comment]
So time was h:mm:ss but you changed to mm:ss. This broke apps. So prob be good idea to revert it back

**Comment by bakerboy448** [comment]
> So time was h:mm:ss but you changed to mm:ss. This broke apps (*adarr). So prob be good idea to revert it back

https://github.com/sabnzbd/sabnzbd/commit/1d3a922a7bb6e8643678dada3a6a595e371258bc#commitcomment-63089839

> Is this change really necessary? It means v3.5 is not compatible with Sonarr/Radarr/Readarr/Lidarr/Prowlarr

> ref https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/Clients/Sabnzbd/JsonConverters/SabnzbdQueueTimeConverter.cs#L26

> This would require patching the aforementioned apps and a new master/main release and would break Sab for hundreds of thousands of users for many months if not years (...looking at Sonarr's delays between develop and main) until new masters/mains are released.

**Pull request merged**
