### PR TITLE
A 404's redirect now keeps the FQDN in place

### PR DESCRIPTION
**Pull request by sanderjo**
PR against 0.8.x develop of https://github.com/sabnzbd/sabnzbd/pull/168

### CODE REVIEW

**Comment by Safihre** [comment]
Missed one where sabnzbd.BROWSER_URL should become browser_url:
https://github.com/sanderjo/sabnzbd/blob/develop/SABnzbd.py#L1659

**Comment by Safihre** [comment]
I see now that sabnzbd.BROWSER_URL also appears in osxmenu.py, sabtray.py and sabtraylinux.py.
Maybe we should keep it :smile:

**Comment by sanderjo** [comment]
I don't know nor did any renaming. 

However, I removed
```
sabnzbd.BROWSER_URL = browser_url
```
from SABnzbd.py thinking it was not needed anymore, but your comment makes indeed clear it is still used elsewhere:
```
$ grep -irn sabnzbd.BROWSER_URL * | grep "py:"
sabnzbd/sabtray.py:126:        launch_a_browser(sabnzbd.BROWSER_URL, True)
sabnzbd/osxmenu.py:664:        launch_a_browser(sabnzbd.BROWSER_URL, True)
sabnzbd/sabtraylinux.py:160:        launch_a_browser(sabnzbd.BROWSER_URL, True)
SABnzbd.py:1659:                if sabnzbd.cfg.web_watchdog() and not is_sabnzbd_running('%s/api?tickleme=1' % sabnzbd.BROWSER_URL, 120):
```
So ... additional commit coming up.

**Comment by shypike** [comment]
Thanks!

**Pull request merged**
