### PR TITLE
Add shortcuts to the config

### PR DESCRIPTION
**Pull request by SKBotNL**
What this adds:
- M: Go back to main menu
- S: Open the search popup
- Navigate through the tabs with the arrow keys

The code is probably not in the right place.

### CODE REVIEW

**Comment by SKBotNL** [comment]
This adds the keybinding wishes from #2038

**Comment by Safihre** [comment]
Now that I see what code is needed, I'm not sure if I'm still a fan.. Does it really add a lot of value to add these shortcuts @sanderjo?
Since so much in the Config is based on using your mouse..

**Comment by sanderjo** [comment]
I use keyboard-shortcuts all the time in Gmail: c, tab, ctrl-enter, j k u.
I would love them in SABnzbd. Now I need a lot of mouse movement and mouse clicks to get to information. For example: Config -> General and Config -> Servers: tiny icons in upper right corner, then move mouse to the left to click in upper bar. Then move mouse to middle. I find that annoying.
My hover-over request, which solves the same problem via easier mouse movements, was rejected.

> Does it really add a lot of value 

For me: yes. 
For other users: I think keyboard-users are a minority

**Comment by SKBotNL** [comment]
Although I also use shortcuts a lot I do agree with @Safihre that the config is mostly based on using your mouse

**Comment by Safihre** [comment]
Will close this for now, as I am not sure I want to add it this way.

**Pull request closed without merging**
