### PR TITLE
Adding animations to Glitter

### PR DESCRIPTION
**Pull request by Safihre**
A little more fun!

### CODE REVIEW

**Comment by shypike** [comment]
Is this animation bearable on slow systems, like an older tablet or smartphone?

**Comment by Safihre** [comment]
It's all css animations, so if the browser supports them (above android 3 and ios 7) it will show them and I can't really filter for device speed. 
But since they all animations only last 0.2 seconds,  they are short so bearable even if stuttered.

**Comment by Safihre** [comment]
@sanderjo 
Is it not also a good idea to display the value of *_EXTERNAL_IPV6* in the dashboard?
External IPv6 connection: Yes/No

**Comment by thezoggy** [comment]
why not show status icon for v4/v6 reachability. and then report back users public ip for each next to it

**Pull request merged**
