### PR TITLE
Add HTML login page

### PR DESCRIPTION
**Pull request by Safihre**
Based on cookies, not CherryPy-sessions. We create an unique cookie based on user-IP, SAB-process-ID and a salt to facilitate log-out functionality (#369).
Yes, this cookie can be stolen when on a public wifi-network (same IP) when not on HTTPS, but when not on HTTPS basic-auth or API-requests (which have the API-key) can also easily be intercepted. Any restart of SAB would in-validate the cookie.

Could also add a 'Remember-me' option if you guys like my implementation.
If it would replace basic-auth we don't need any new translations (except 'Log out', but this can automatically be translated from other packages on Launchpad).

@shypike Since it's a new feature, I understand this is not anymore for the 0.8.0 release :)

image

### CODE REVIEW

**Comment by thezoggy** [comment]
while your at it, should add the whole 'whitelist' local ip features so only outsiders get the prompt... for those that want the pw prompt but only when they access remotely...

example code: https://github.com/midgetspy/Sick-Beard/pull/151/files

**Comment by thezoggy** [comment]
also need to check to see if this works with web_root / reverse proxy.. and if changing sab from http<>https

**Comment by Safihre** [comment]
I tested HTTPS, works fine! Maybe someone else can test reverse proxy (@sanderjo, if he has time).
For the white-listing, this would only work with the HTML login.
I decided to add an extra option to *External internet access* called: 
*Full Web interface - Only external access requires login* (still working on the python-code)

**Comment by sanderjo** [comment]
I tested like below (correct?), and I get a working, non-popup login screen from SABnzbd behind my Apache2-as-HTTPS-proxy.

screenshot from 2016-01-24 19 50 45


```
mkdir safihre-sabnzbd
cd safihre-sabnzbd/
git clone https://github.com/Safihre/sabnzbd.git
cd sabnzbd/
git branch -a
git checkout newlogin

sudo service sabnzbdplus stop
./SABnzbd.py 
```

**Comment by Safihre** [comment]
And usage was fine? Going to Config pages etc :)

**Comment by Safihre** [comment]
So, I added the 'Remember me' checkbox, although after a SABnzbd restart or change of IP, nothing will be remembered.

I also added the **'Full Web interface - Only external access requires login'** option and the back-end code, since these things are intertwined: Without **Full Web interface** turned on, nothing will show anyway.

**Comment by Safihre** [comment]
I made the HTML-login the default (with the option in Specials to switch it off). Because the 'Only external access requires login' only works with the HTML login.
Otherwise we have to explain how that option would only work with HTML login turned on etc.
We can always drop that commit from this PR in case it's a bad idea?

**Comment by shypike** [comment]
@Safihre I think making HTML-login the default is fine. I think most people will expect a login page instead of the rare basic login prompt.

**Comment by Safihre** [comment]
@thezoggy you maybe have time for that new or better old logo? :yum:
It looks a little odd now with the black shadow.

**Comment by shypike** [comment]
@Safihre Isn't "Login" a better button name than "Send"?
What is the meaning of the checkmark before the text?

**Comment by Safihre** [comment]
The checkmark is gone and I made it say "Log in", indeed better but required another new text so didn't do it before :) I just rebased this changes on top of the last commits.

This how it looks now:
image

**Comment by thezoggy** [comment]
a very common thing is people forgetting their sab pw/not expecting it when they login (no clue how).. but anyways we should maybe offer a link to the wiki from this page on how to reset their password ( http://wiki.sabnzbd.org/faq#toc21 ) -- note we really should make a proper page since we dont want this page to change from this point forward to ensure that whatever we do link remains good.

**Comment by thezoggy** [comment]
@Safihre ive completely dropped the ball on the logo :( let me go tinker with some stuff

**Comment by Safihre** [comment]
I added an anchor to the wiki so now it's:
http://wiki.sabnzbd.org/faq#why-login

And made it this:
image

**Comment by thezoggy** [comment]
lol that FAQ page needs some lovin, http://wiki.sabnzbd.org/faq#toc8

**Comment by shypike** [comment]
@thezoggy I'm sure it would return the love you give it :)

**Pull request merged**
