### PR TITLE
Correctly display speedlimit

### PR DESCRIPTION
**Pull request by Safihre**
Fixing #388

### CODE REVIEW

**Comment by Safihre** [comment]
@shypike @thezoggy Now correctly done in the API so it will work for all skins!

**Comment by Safihre** [comment]
Updated the whole speedlimiter for Plush, it was just soo user-unfriendly this way.
Now you can select how you want it to display and input your speedlimit, in %, KB/s or MB/s.
Changing your option will update the value immediately.
Also for some reason hitting enter after updating the value didn't save it (did it before 0.8?), that's fixed now.
image

**Comment by shypike** [comment]
It's not quite right yet.
Scenario 1:
- Set max speed to be 10M.
- set speed to 50% in Glitter (shows as 50%/5M
- speed in Plush, shows as 51%, 5222.4K, 5.1M <==ROUNDING ERROR?
- set speed to 3M in Plush, Glitter will show 30% (3.0 MB/s)
- get_speedlimit API-call delivers 30.0
Scenario 2:
- Set max speed to be 150G (I should be so lucky)
- set speed to 50% in Glitter, shows as 50% (75GB/s)
- speed in Plush, shows as 50%, 78643200K, 76800M <==ROUNDING ERROR?

**Comment by Safihre** [comment]
Small other fixes now also included.

**Comment by shypike** [comment]
Thank you!!

**Pull request merged**
