### PR TITLE
Interface fixes part 13

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by shypike** [comment]
All of these commits for 1.0.0 ??

**Comment by Safihre** [comment]
No only 3ae85a4.
Possibly 812eaca, since it's in Plush for 1.0.0 but was missing from Glitter.
Rest can be for 1.0.1+!

**Comment by thezoggy** [comment]
upon thinking about the whole history thing, thought up some ideas: https://github.com/sabnzbd/sabnzbd/issues/478

**Comment by shypike** [comment]
Merged, thanks.

**Pull request closed without merging**
