### PR TITLE
add bash completion

### PR DESCRIPTION
**Pull request by jcfp**
This change adds an autocomplete file for SABnzbd.py. It only actually does something if installed to a location where bash expects it (intended use), or when the user manually sources the file into bash; please do include in releases just like the desktop and service files.

To test, run a bash shell, source the autocomplete file, then use one of the recognized forms of the sabnzbd command and hit the TAB key one or more times:
```
source linux/sabnzbd.bash-autocomplete
SABnzbd.py <TAB>
SABnzbd.py -<TAB>
SABnzbd.py --<TAB>
```
Command-line options are automatically suggested and completed, argument values suggested, and directories and supported file types autocompleted for loading nzb files from the command line.

It deals with every option that takes arguments manually rather than parsing the program's --help output, as the latter is really slow for anything using interpreted languages (noticable lag when hitting TAB to start autocompletion).

For the --server option, only the possible argument formats are indicated rather than trying to hint actual values such as hostnames and port. The multitude of possible formats makes an autocomplete function for actual hostnames, ipv4 and ipv6 addresses and ports too complex to be worthwhile.

### CODE REVIEW

**Comment by Safihre** [comment]
So this only works if the user manually runs the `source` command?

The file should be included automatically in the source distribution: https://github.com/sabnzbd/sabnzbd/blob/b42e600285b663d69487372163f364775dbaa775/builder/package.py#L437

But you can check that in the build output.

**Comment by jcfp** [comment]
> * how/when are directories useful as input for SAB?

The program takes one or more (collections of) nzb files to load as command line arguments. The autocomplete for that is limited to directories and a list of accepted extensions.

> So this only works if the user manually runs the `source` command?

That's the simple way to load this for testing purposes. In typical use, the file would be installed in locations where bash automatically finds it, system-wide by a package in /usr/share/bash-completion/completions/ or in a local directory such as ~/.local/share/bash-completion/completetions by an individual user.

**Comment by sanderjo** [comment]
> system-wide by a package in /usr/share/bash-completion/completions/

Ah, that is how it works! Cool.

On my Ubuntu, /usr/share/bash-completion/completions/ contains 900+ entries. For example for curl and wget.

And thus soon for sabnzbdplus and SABnzbd.py.

**Comment by jcfp** [comment]
is it me or does the file in the rc1 -src.tar.gz have windows line endings all of a sudden?

**Comment by Safihre** [comment]
It seems we only "correct" line endings for a specific set of file extensions:
https://github.com/sabnzbd/sabnzbd/blob/develop/builder/package.py#L448-L453

**Comment by Safihre** [comment]
@jcfp I moved the source building to the macOS job, now the line endings are fine.
https://github.com/sabnzbd/sabnzbd/commit/1894ed72e38aae5d4d870e58f879fd8e831e6a9a
I could have made it's own job, but that seems like a waste of resources (installing deps etc).

**Pull request merged**
