### PR TITLE
Do not calculate history every API call and more fixes

### PR DESCRIPTION
**Pull request by Safihre**
Investigating #478 I found the only time when the history is really updated is when the ```action_line``` is changed or when something is deleted.
And it works like a charm!
Is even faster when doing the 500ms delay in combination with this, but that requires some more work to fine tune.
image

### CODE REVIEW

**Comment by shypike** [comment]
Nifty trick. A little bit dirty because a true optimization might be better.
Does this work for smpl, Plush and other API users (without changes)?
I cannot figure out what LAST_HISTORY_CALL actually carries. Last time someone used the API or last time the history was changed?

**Comment by thezoggy** [comment]
hes setting the last time 'set_action_time' was called.. which happens on certain events.. when something is pp..  aka: `nzo.set_action_line()` is called.

**Comment by Safihre** [comment]
Indeed I looked at the only time something happens with the queue and which functions are used then, and ```set_action_line``` is the common denominator! So ```LAST_HISTORY_CALL``` only houses a timestamp.
Also on Glitter preload the function is called without a ```last_history_call```, so always the freshest info and then only when something happens it will update. So also when multiple devices are viewing at same time, it will work since any pp-event or delete-event will trigger an update on any device.

@thezoggy only when a skin/call sets the ```&last_history_call``` parameter it is actually evaluated, otherwise it just behaves as normal and returns everything.

**Comment by Safihre** [comment]
Found one more place that needed to update the ```LAST_HISTORY_CALL``` (see 1daa9e6) and accidentally pushed some unrelated commits in this branch :hamster: 
Maybe this can be merged (and #515) so others can test if any cases were missed?

I already noticed that idle CPU usage with "normal" sized queue/history lowered from 1% to 0.4% on my laptop's i5. So probably this will be even more beneficial for less powered devices.

**Comment by shypike** [comment]
Which commits actually need to go into "develop"?

**Comment by Safihre** [comment]
You mean if any should go into 1.0.1? I intended this feature  for develop, not for 1.0.1, since it might deserve some extra testing by others to make sure there are no unexpected freezes of the history. 
The other commits apply to Tabbed and Compact layouts, which are not in 1.0.x.

**Comment by shypike** [comment]
You wrote "accidentally pushed some unrelated commits in this branch", but that remark wasn't valid for "develop".
So, only 597efc661ab8349c2a31049c932d5c21eb53b507 and 1daa9e66f686fb63dcf7717eea05b237dbee514e may go into 1.0.1 ?

**Comment by Safihre** [comment]
Yes, but not sure if there might be some merge conflicts because of all the changes to glitter.js.
 And again can't promise the implementation is without faults yet..

**Comment by shypike** [comment]
@Safihre In that case, this will not go into 1.0.1: safe bugfixes only.

**Comment by Safihre** [comment]
Exactly what I was thinking  :)

**Pull request merged**
