### PR TITLE
Feature/cherrypy5

### PR DESCRIPTION
**Pull request by shypike**
Update CherrryPy to official 5.1.0 release.

Re-apply almost all previous patches.
So far, CherryPy 5 seems to work fine.

### CODE REVIEW

**Comment by Safihre** [comment]
In a PR because you're not sure about it? Should we test it?

**Comment by shypike** [comment]
@Safihre 
Please do, if you have the time.
Because CherryPy upgrades are always tricky, I decided to be careful.
So far, it seems to behave nicely.
If there are no real issues, I want this in 1.1.0 and hopefully the weird CP crashes some people have, will be gone.

**Comment by sanderjo** [comment]
git question: how should I switch to that branch? AFAIK it's not in develop? I tried a few things, but that seems not to work.

```
sander@flappie:~/git/sabnzbd-22maart2016$ git branch -a
* develop
  remotes/origin/0.6.x
  remotes/origin/0.7.x
  remotes/origin/1.0.x
  remotes/origin/HEAD -> origin/develop
  remotes/origin/R0.6.10
  remotes/origin/develop
  remotes/origin/feature/cherrypy5
  remotes/origin/https_test
  remotes/origin/master
sander@flappie:~/git/sabnzbd-22maart2016$ cat cherrypy/VERSION.txt 
CherryPy 3.8.0 Official distribution: https://pypi.python.org/packages/source/C/CherryPy/CherryPy-3.8.0.tar.gz
The folders 'tutorial', 'test' and 'scaffold' have been removed.
This file has been added.
A patch is required to enable proper Bonjour/Zeroconfig support.
```
and
```
sander@flappie:~/git/sabnzbd-22maart2016$ git branch remotes/origin/feature/cherrypy5
sander@flappie:~/git/sabnzbd-22maart2016$ git branch
* develop
  remotes/origin/feature/cherrypy5
sander@flappie:~/git/sabnzbd-22maart2016$ 
sander@flappie:~/git/sabnzbd-22maart2016$ cat cherrypy/VERSION.txt 
CherryPy 3.8.0 Official distribution: https://pypi.python.org/packages/source/C/CherryPy/CherryPy-3.8.0.tar.gz
The folders 'tutorial', 'test' and 'scaffold' have been removed.
This file has been added.
A patch is required to enable proper Bonjour/Zeroconfig support.

sander@flappie:~/git/sabnzbd-22maart2016$ git branch cherrypy5
sander@flappie:~/git/sabnzbd-22maart2016$ cat cherrypy/VERSION.txt 
CherryPy 3.8.0 Official distribution: https://pypi.python.org/packages/source/C/CherryPy/CherryPy-3.8.0.tar.gz
The folders 'tutorial', 'test' and 'scaffold' have been removed.
This file has been added.
A patch is required to enable proper Bonjour/Zeroconfig support.

```

**Comment by shypike** [comment]
git checkout -b feature/cherrypy5

**Comment by sanderjo** [comment]
Without the "-b" it works:

```
sander@flappie:~/git/sabnzbd-22maart2016$ git branch -a
* develop
  remotes/origin/0.6.x
  remotes/origin/0.7.x
  remotes/origin/1.0.x
  remotes/origin/HEAD -> origin/develop
  remotes/origin/R0.6.10
  remotes/origin/develop
  remotes/origin/feature/cherrypy5
  remotes/origin/https_test
  remotes/origin/master
sander@flappie:~/git/sabnzbd-22maart2016$ git checkout feature/cherrypy5
Branch feature/cherrypy5 set up to track remote branch feature/cherrypy5 from origin.
Switched to a new branch 'feature/cherrypy5'
sander@flappie:~/git/sabnzbd-22maart2016$ cat cherrypy/VERSION.txt 
CherryPy 5.1.0 Official distribution: https://pypi.python.org/packages/source/C/CherryPy/CherryPy-5.1.0.tar.gz
The folders 'tutorial', 'test' and 'scaffold' have been removed.
This file has been added.
A patch is required to enable proper Bonjour/Zeroconfig support.

sander@flappie:~/git/sabnzbd-22maart2016$ 
```
Thanks.

**Comment by Safihre** [comment]
Working fine here the past 2 days, but I guess my boring Windows10 setup with CP and Sonarr is not exotic enough to really be a test case :sweat_smile:

**Comment by thezoggy** [comment]
you need to fetch first before you can pull/checkout.
http://stackoverflow.com/questions/1783405/checkout-remote-git-branch

**Comment by thezoggy** [comment]
@shypike  are all of your 'fixes' submitted as bugs to cherrypy ? (i only see one listed)

**Comment by thezoggy** [comment]
I see you have: ` Patch CherryPy 5.1.0: to avoid Unicode bugs in PyOpenSSL 0.14 ` 
which is why I'd suggest upgrading your build boxes to use pyOpenSLS 0.15.1

**Comment by shypike** [comment]
@thezoggy We discussed this before. For Windows I'm stuck with eGenix, who are stuck with PyOpenSSL 0.13. I'll send you the method to create the binary for Windows.

**Comment by thezoggy** [comment]
never heard of egenix before.. but looks like they just came out with an update:
http://www.egenix.com/company/news/eGenix-pyOpenSSL-Distribution-0.13.14.html

**Comment by Safihre** [comment]
Tested all the patches and used it for the past 2 weeks, no problems at all.

**Pull request merged**
