### PR TITLE
iperf3 internet speed test for linux (including docker)

### PR DESCRIPTION
**Pull request by sanderjo**
On systems with high speed Internet and low CPU speed, SABnzbd's current Internet speed tester gives too low values.

This PR uses iperf3 to get the real Internet speed. The iperf3 module is available on Linux (and thus docker).

If iperf3 is not available, the existing SAB Internet speed test is used.

**Example results**

On a VPS, with an OK CPU, with quite fast Intern (2+ Gbps):

With old measurement based on HTTP download(s) ... "725 Mbps" : 

image

With iperf3 within SABnzbd ... "2228 Mbps", which is 3 times higher, and the correct speed:

image

### CODE REVIEW

**Comment by jeffgeorge** [comment]
Two questions:
1. Do we know if Clouvider is cool with having their servers integrated with an open-source project? I found [this frontend](https://as62240.net/speedtest) to all (?) of their geographically distributed iperf3 servers, but this intended for personal use, not necessarily for _integration_. They also claim in their footer that "These servers are connected at 10Gbps best effort, during peak times limited throughput may be seen", and due to the nature of iperf3 it can only do one test at a time per server per port. In just my manual testing I've already hit congestion. From peeking at Cloudflare logs, we see roughly ~5k speedtests daily, and some days can see upwards of 10k (if somebody gets excited), and that's ok because we're _paying_ Cloudflare and they're explicitly built to handle ludicrous concurrency.
2. Do we know if this is really going to solve our problem? Just from personally testing these, I'm seeing tons of variability based on geography.

Some test results from my residential symmetrical gigabit fiber connection:
* [Ookla's official `speedtest` CLI](https://www.speedtest.net/apps/cli) - Closest ISP-owned node - 934 Mbps
* Ookla's official `speedtest` CLI - Closest general node - 914 Mbps
* `iperf3 -c nyc.speedtest.clouvider.net -p 5208` - 575 Mbps
* `iperf3 -c ash.speedtest.clouvider.net -p 5208` - 194 Mbps
* `iperf3 -c atl.speedtest.clouvider.net -p 5208` - 13.6 Mbps (This is their closest server to me geographically??)
* SABnzbd Wrench Speedtest - 551 Mbps
* SABnzbd Test Download - 800-850 Mbps

Is it worth hammering these iperf3 servers for _maybe_ 5% more accurate tests that may still be wildly inaccurate as a whole?

**Comment by sanderjo** [comment]
> Some test results from my residential symmetrical gigabit fiber connection:

You're doing it wrong, @jeffgeorge 

`iperf3 -R -P15 -p 5207 -t3 -4  --format m -c fra.speedtest.clouvider.net | grep receiver | tail -1
`

**Comment by jeffgeorge** [comment]
Ahhh, I wasn't running with enough concurrency, that gets far more reliable results.

My first concern still stands, though. Are they cool with us sending a nontrivial amount of traffic their direction?

**Comment by sanderjo** [comment]
> My first concern still stands, though. Are they cool with us sending a nontrivial amount of traffic their direction?

I mailed them yesterday and today.

A workaround could be: a user can fill out the iperf3 server(s) to be used. Then it will only be used by a small amount of users.

**Comment by sanderjo** [comment]
Two mails to clouvider, no reaction. 

Maybe I should ask leaseweb, as they have a lot of servers around the globe:

```
~$ lynx --dump https://raw.githubusercontent.com/R0GGER/public-iperf3-servers/main/README.md | grep leaseweb
| iperf3 -c speedtest.mtl2.ca.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.chi11.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.dal13.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.lax12.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.mia11.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.nyc1.us.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.phx1.us.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.sfo12.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.sea11.us.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.wdc2.us.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.hkg12.hk.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.tyo11.jp.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.sin1.sg.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.fra1.de.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.lon1.uk.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.lon12.uk.leaseweb.net -p 5201-5210        |    -R, -6
| iperf3 -c speedtest.ams1.nl.leaseweb.net -p 5201-5210         |   -R, -6,
| iperf3 -c speedtest.ams2.nl.leaseweb.net -p 5201-5210         |    -R, -6
| iperf3 -c speedtest.syd12.au.leaseweb.net -p 5201-5210        |    -R, -6
```



With nice performance:

```
$ iperf3 -R -c speedtest.ams1.nl.leaseweb.net -p 5201-5210
Connecting to host speedtest.ams1.nl.leaseweb.net, port 5201
[  5] local 2a05:xxx port 42558 connected to 2001:1af8:5300:a018::77 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   457 MBytes  3.83 Gbits/sec    0   3.93 MBytes
[  5]   1.00-2.00   sec   412 MBytes  3.46 Gbits/sec  3134    632 KBytes
[  5]   2.00-3.00   sec   324 MBytes  2.72 Gbits/sec  225    487 KBytes
[  5]   3.00-4.00   sec   286 MBytes  2.40 Gbits/sec    0    826 KBytes
[  5]   4.00-5.00   sec   288 MBytes  2.41 Gbits/sec  213    690 KBytes
[  5]   5.00-6.00   sec   344 MBytes  2.88 Gbits/sec   91    752 KBytes
[  5]   6.00-7.00   sec   302 MBytes  2.54 Gbits/sec  225    625 KBytes
[  5]   7.00-8.00   sec   308 MBytes  2.58 Gbits/sec  180    731 KBytes
[  5]   8.00-9.00   sec   291 MBytes  2.44 Gbits/sec   90    826 KBytes
[  5]   9.00-10.00  sec   316 MBytes  2.65 Gbits/sec  180    876 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  3.25 GBytes  2.79 Gbits/sec  4338             sender
[  5]   0.00-10.00  sec  3.25 GBytes  2.79 Gbits/sec                  receiver

```

**Comment by Safihre** [comment]
Using `sabctools` I made our "own" low-level HTTP request with super-fast SSL readouts that just dumps the data.
With this approach we get much better results, even on @sanderjo's  2.5GBps line!
I also made the test not run in paralel to the disk-speed test, as it's just too much for poor Python to handle. The user will just have to wait a little more.
The test is capped at 4 seconds, combined with the ~1 second for the disk-checks and the DNS/IP-address lookups the total time will be around 10 seconds maximum. This I added to the tooltip so users are aware.

**Comment by thezoggy** [comment]
i have 1G fiber (and only 1G nic to wan), with speedtest-tracker docker (python -> ookla)  i see 940 Mbps pretty consistently. 

sab speed test (before this update), generally resulted in ~90MB/s which is close but little off but I assume due to only doing such small files and rounding/estimations...
```
2023-12-06 18:28:00,635::DEBUG::[getipaddress:87] DNS Lookup = True (in 0.01 seconds)
2023-12-06 18:28:04,952::DEBUG::[internetspeed:50] Basic measurement, with small download:
2023-12-06 18:28:04,968::DEBUG::[internetspeed:24] URL is https://sabnzbd.org/tests/internetspeed/5MB.bin
2023-12-06 18:28:05,317::DEBUG::[getperformance:66] Pystone performance = 522435 (in 0.37 seconds)
2023-12-06 18:28:05,482::DEBUG::[internetspeed:36] Downloaded bytes: 5242880
2023-12-06 18:28:05,482::DEBUG::[internetspeed:37] Duration in seconds: 0.493678
2023-12-06 18:28:05,482::DEBUG::[internetspeed:54] Speed in MB/s: 10.13
2023-12-06 18:28:05,482::DEBUG::[internetspeed:79] https://sabnzbd.org/tests/internetspeed/20MB.bin
2023-12-06 18:28:05,482::DEBUG::[internetspeed:24] URL is https://sabnzbd.org/tests/internetspeed/20MB.bin
2023-12-06 18:28:05,719::DEBUG::[internetspeed:36] Downloaded bytes: 20971520
2023-12-06 18:28:05,719::DEBUG::[internetspeed:37] Duration in seconds: 0.236863
2023-12-06 18:28:05,719::DEBUG::[internetspeed:81] Speed in MB/s: 84.44
2023-12-06 18:28:05,720::DEBUG::[internetspeed:79] https://sabnzbd.org/tests/internetspeed/20MB.bin
2023-12-06 18:28:05,720::DEBUG::[internetspeed:24] URL is https://sabnzbd.org/tests/internetspeed/20MB.bin
2023-12-06 18:28:05,886::DEBUG::[diskspeed:52] Disk speed of /downloads/incomplete = 711.12 MB/s (in 0.05 seconds)
2023-12-06 18:28:05,954::DEBUG::[internetspeed:36] Downloaded bytes: 20971520
2023-12-06 18:28:05,954::DEBUG::[internetspeed:37] Duration in seconds: 0.234233
2023-12-06 18:28:05,954::DEBUG::[internetspeed:81] Speed in MB/s: 85.39
2023-12-06 18:28:05,954::DEBUG::[internetspeed:84] Internet Bandwidth = 85.39 MB/s (in 0.99 seconds)
2023-12-06 18:28:06,462::DEBUG::[diskspeed:52] Disk speed of /downloads/complete = 742.38 MB/s (in 0.05 seconds)
```

while during actual downloading sab hits ~110MB/s, so close to the 940 Mbps that aligns with speedtests..

now after this change, sab speedtest now wronly overly estimates speed of 132.85MB/s, which technically is impossible it to be higher than max line rate of a 1G nic let alone real world actual wan provisioned link. 
```
2023-12-06 18:29:48,037::DEBUG::[getperformance:66] Pystone performance = 522295 (in 0.37 seconds)
2023-12-06 18:29:48,601::DEBUG::[diskspeed:52] Disk speed of /downloads/incomplete = 716.35 MB/s (in 0.05 seconds)
2023-12-06 18:29:49,178::DEBUG::[diskspeed:52] Disk speed of /downloads/complete = 719.91 MB/s (in 0.05 seconds)
2023-12-06 18:29:49,198::DEBUG::[happyeyeballs:156] Available addresses for sabnzbd.org (port=443): 3 IPv4 and 0 IPv6
2023-12-06 18:29:49,202::DEBUG::[happyeyeballs:90] Happy Eyeballs connected to 104.26.2.117 (sabnzbd.org) in 3ms
2023-12-06 18:29:49,202::INFO::[happyeyeballs:188] Quickest IP address for sabnzbd.org (port=443): 104.26.2.117 (sabnzbd.org)
2023-12-06 18:29:53,266::DEBUG::[internetspeed:104] Internet Bandwidth = 132.85 MB/s - 1069.41 Mbps (in 4.00 seconds)
```

**Comment by Safihre** [comment]
Interesting. Guess some rounding error somewhere, as it's only a few percent different. Will tweak a bit.

**Comment by sanderjo** [comment]
I connected to my 1GigE port (on my 4Gbps Internet connection), measured, and got this:

```
$ cat ~/.sabnzbd/logs/sabnzbd.log | grep -i internetspeed
2023-12-07 09:50:32,549::DEBUG::[internetspeed:104] Internet Bandwidth = 124.57 MB/s - 1002.80 Mbps (in 4.00 seconds)
2023-12-07 09:50:44,037::DEBUG::[internetspeed:104] Internet Bandwidth = 123.14 MB/s - 991.28 Mbps (in 4.00 seconds)
2023-12-07 09:50:52,113::DEBUG::[internetspeed:104] Internet Bandwidth = 119.80 MB/s - 964.43 Mbps (in 4.00 seconds)
2023-12-07 09:51:51,573::DEBUG::[internetspeed:104] Internet Bandwidth = 117.11 MB/s - 942.76 Mbps (in 4.00 seconds)
```
Looks good

iperf3
```
sander@zwart2204:~$ iperf3 -R -P15 -p 5207 -t3 -4  --format m -c fra.speedtest.clouvider.net | grep receiver | tail -1
[SUM]   0.00-3.00   sec   334 MBytes   935 Mbits/sec                  receiver
sander@zwart2204:~$ iperf3 -R -P15 -p 5207 -t3 -4  --format m -c ams.speedtest.clouvider.net | grep receiver | tail -1
[SUM]   0.00-3.00   sec   336 MBytes   940 Mbits/sec                  receiver

```
A bit lower

So: deduct a few percent from the SAB measurement is possible, but ... why? It's a application level, so the real bits are even higher. And no a MB versus MiB problem. So what is going on? Timing thing? Measurement thing?

**Comment by thezoggy** [comment]
for the final calc, why are we doing speed * 8.05 instead of just 8?

ran test several times, seeing slightly lower numbers than before but still technically higher than actual bandwidth but probably within reason:
```
2023-12-07 10:03:00,884::DEBUG::[internetspeed:104] Internet Bandwidth = 122.44 MB/s - 985.60 Mbps (in 4.00 seconds)
2023-12-07 10:03:09,799::DEBUG::[internetspeed:104] Internet Bandwidth = 120.08 MB/s - 966.61 Mbps (in 4.00 seconds)
2023-12-07 10:03:23,085::DEBUG::[internetspeed:104] Internet Bandwidth = 122.16 MB/s - 983.42 Mbps (in 4.00 seconds)
2023-12-07 10:03:46,314::DEBUG::[internetspeed:104] Internet Bandwidth = 119.55 MB/s - 962.34 Mbps (in 4.00 seconds)
2023-12-07 10:03:59,454::DEBUG::[internetspeed:104] Internet Bandwidth = 120.58 MB/s - 970.64 Mbps (in 4.00 seconds)
2023-12-07 10:04:11,728::DEBUG::[internetspeed:104] Internet Bandwidth = 122.58 MB/s - 986.80 Mbps (in 4.00 seconds)
```

**Comment by Safihre** [comment]
@sanderjo is that 8.05 normal? I thought it should be 8, but copied this from the old test.

The estimation difference is because of timing, because there is both the actual receiving of data on the socket and then when we do the SSL decoding. So it depends when you measure the time, before or after the decoding. 
We have to do the decoding to clear the socket data queued by the OS.  Probably iperf can do it at a lower lever.

**Comment by thezoggy** [comment]
side question, if sab is currently downloading things... and the user loads up to do the speed test...  does it stop said downloads to focus on this new test or does it just suffer while things are downloading.  
if so, we might want to detect if queue isnt empty/paused to prevent users from running the speed test and getting unreliable speed?

**Comment by Safihre** [comment]
Untill now the speed test hasn't paused the queue.

**Comment by thezoggy** [comment]
to be clear, im not saying the speed test should pause the queue. just that it should prevent being able to run if the queue isnt paused/empty.

**Comment by sanderjo** [comment]
> just that it should prevent being able to run if the queue isnt paused/empty.

So ... "no, you first have to empty your queue before you can run a speed test".  "I've tens of downloads in my queuue". "Yes".

**Comment by Safihre** [comment]
Great 👍

**Pull request closed without merging**
