### PR TITLE
sab 0.8.x -- config tweaks

### PR DESCRIPTION
**Pull request by thezoggy**
Add the module/binary information to the config root page since it can be a pain to see it if you dont access the log file or console directly..  

Some of the wiki pages for -0-8 did not exist, started to create them by using the 0-7 pages then updating...

### CODE REVIEW

**Comment by Safihre** [comment]
Talking about the Wiki, @thezoggy made this very detailed page about the API: http://thezoggy.github.io/sabnzbd/api/
Why are we not using it @shypike ?

**Comment by thezoggy** [comment]
that api page is really really old.. we were going to go with a readthedocs / docgen auto thing at one point but that never took off.. sab's api is horribly documented.. so its just a crazy task to start from scratch especially if you want to provide examples thats 'safe' :)

**Comment by Safihre** [comment]
So what do you suggest? Expand your version maybe best?

**Comment by thezoggy** [comment]
not sure, but prob should move this conversation (api doc) to its own github issue

**Comment by Safihre** [comment]
Back to your PR: I tried it and liked it! Wondered if it really needed to be on tabs? This way it also hides the support part, and the page doesn't become that long (compared to the other Config-pages) when all is on 1 page. Also limits the need for extra translations..

**Comment by thezoggy** [comment]
I had it all on the page but then it was getting a bit long.. so I went to tabs so would be shorter and easier to segment. Now segmenting the 'support' section to its own tab I figure may get some mixed reviews since some may want that as the default tab while others wouldnt... also the config root page is not in the navbar thus you can only get to this on the way to the config page from a skin.... so that support info probably isnt used a lot and may be best off being relocated else where / add config root page to the nav bar.

**Comment by Safihre** [comment]
Adding the root page to the nav-bar isn't going to fit, it barely fits in English but in other languages I already had to use a smaller version of the logo to let the current pages to fit.
I would still vote for all on 1 page, but that's just me ;-)

**Comment by thezoggy** [comment]
It is all on one page...

-----Original Message-----

**Comment by Safihre** [comment]
Without tabs I meant :)

**Comment by thezoggy** [comment]
well just copy the tables out of the tab content and you can see...  on linux it has a few extra rows (nice/ionice) and can get a little long.. but not a huge deal i just know you were trying to make everything mobile size.. why i did the tabs

**Comment by Safihre** [comment]
Actually, why even show all this information on Windows and OSX? These come with all binaries included in the package. 
I would only show them for Linux or when they are not found (for development purposes, since yEnc and pyOpenSSL could be missing).

**Comment by thezoggy** [comment]
not everyone installs using the binaries or checks out the source from git correctly as we found. like i run from git on windows, thus i do want to see the modules.. and if the binaries being used are the 64bit versions.. etc.

**Comment by shypike** [comment]
Can you rebase to the latest "develop"?

**Comment by thezoggy** [comment]
sure thing, also will look again about not doing tabs so we dont introduce more translations / make safihre happy :)

**Comment by Safihre** [comment]
Appreciated ;-)
I still think when someone is running the binary version, we shouldn't show all this info, only when on Linux or Git. So when ```$build == 'unknown' or (not $nt and not $darwin)``` 
For the regular folk it's just too much information I feel..

**Comment by shypike** [comment]
Shall I pick this up for 1.0.0 Final?
Seems low risk; dangerous words...

**Comment by thezoggy** [comment]
let me rebase it and work on it some more..  hopefully my home internet is fixed today

**Comment by Safihre** [comment]
And it might need new translations?

**Comment by shypike** [comment]
@Safihre It's mostly tech info, missing translations isn't so bad.
@thezoggy I already fixed the Wiki links, so you can remove commit 4f3634bdda591fc7210609f639ab4d4ab7fbef98

**Comment by thezoggy** [comment]
@shypike will do...

**Comment by thezoggy** [comment]
alright redid it, no more tabs.. and ended up dropping most of it.. since the binary lines really dont say which one sab will use.. thus i dont want to cause more questions than it would answer.

sab12

**Comment by Safihre** [comment]
Huh, why font awesome? We already have and use glyphicons from Bootstrap and never images. Why include another icon font?

**Comment by thezoggy** [comment]
because images are quite inefficient at times, you have to make sacrifices when dealing with what bg color to use.. or make multiple images.. being able to change the 'icon' color on hover / action / scale depending on size.. just makes sense. I'd like for us to get away from glyphicons eventually.

**Comment by Safihre** [comment]
Glyphicons is an icon font just like Fontawesome that I already use instead of images. The only image that is in the Config is the SABnzbd logo..
For just 2 icon's you would include all these extra icon font-files while you could have just used:
```html
<span class="glyphicon glyphicon-resize-full"></span>
<span class="glyphicon glyphicon-chevron-up"></span>
```

Bootstrap 4 will indeed not include Glyphicons any more, but then we can switch all (Glitter/Config/Wizard) at once to Fontawesome. Not include 2 icon fonts just for 2 icons on 1 page now for the final..

**Comment by thezoggy** [comment]
i agree that font-awesome is overkill if we were to only use it for the two icons on the config root (which are in glyphicons as well). font-awesome does have far more icons than what bootstrap has.. which i think could benefit us greatly.. so anyways there are a few icons in glitter that dont show a hover state.. why i was thinking it was still images (last time i messed with bootstrap was 2.x)

**Comment by thezoggy** [comment]
feel free to throw this in before 1.0.0 final

**Comment by Safihre** [comment]
If this will go into 1.0.0, it needs some polishing because it doesn't match the rest of the new config. Sorry to scrutinize so much, but just spend quite a lot of time on that new config :relieved: 

image

**Comment by thezoggy** [comment]
yes your being very nit picky but i'll humor you

the '+ Info' is what the translation shows.. I am just using whats available. thought you were anti creating more translations

the table does not have a border as its bootstrap and not custom css like the rest of the config, and the way you changed the custom css its a pain as its an alpha border and creates a funky effect if i try to apply it here

colors are just colors, green means proceed..  dunno what you have against green :)

two different tables with different content, of course they wont be aligned..  would have to apply css/bootstrap grid to specifically limit widths.. 

added collapse/fullscreen because of your love of wanting everything to be mobile friendly, and you gotta do it somewhere to show how its useful as I didn't want to go modify all the config pages with this 30 sec pull request

**Pull request closed without merging**
