### PR TITLE
Check if host is valid: an IP address, or a name/FQDN that resolves

### LINKED ISSUE #2252: SABnzbd's GUI accepts non-valid IP address or name as input for Config -> General -> SABnzbd Host
Triggered by https://forums.sabnzbd.org/viewtopic.php?p=127870#p127870

SAB's GUI accepts `0.0.0.0.` (note the trailing dot) and other incorrect as input, but then refuses startup.

I'll come up with a solution, probably a `validation=` in https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/cfg.py , with help of `socket.getaddrinfo('::', None, socket.AF_INET)` and `socket.getaddrinfo('::', None, socket.AF_INET6)`

Looks useful for the newsservers names too.

### PR DESCRIPTION
**Pull request by sanderjo**
Closes #2252

Refuses invalid input for host; should be a syntax-correct IP address, or a hostname that resolved to an IP address. Avoids a non-working on restart of SAB.
Does not check whether the IP address is on this host. So filling out 6.7.8.9 will be accepted, but still makes SAB non-working on restart

### CODE REVIEW

**Comment by sanderjo** [comment]
(sorry for the formatting mess: new pycharm, auto-black not working, so did a manual black command, which messed it up)

I need some help: to want validate_host() to refuse incorrect host names, but returning None does not work. And even returning "127.0.0.1" does not work. So what am I doing wrong?

**Comment by Safihre** [comment]
> (sorry for the formatting mess: new pycharm, auto-black not working, so did a manual black command, which messed it up)
> 
> I need some help: to want validate_host() to refuse incorrect host names, but returning None does not work. And even returning "127.0.0.1" does not work. So what am I doing wrong?

For a validator, the first return value is the error to display, the second return value is the value that will be stored.
This way you can show an error _and_ automatically set a safe default value.
If the second return value is `None`, the current value that was already in the config-file will be preserved.

So try:
```python
return T('Invalid server address.'), None`
``` 
The text `Invalid server address.` is an existing translation, so that would make things easier.

**Comment by sanderjo** [comment]
I did that (see latest commit). 

I start with "127.0.0.1" filled out.
When I fill out something very wrong ("not good at all") and click Save, that input "not good at all" just stays there. I had hoped it would return to the former value. The 'good' news: when clicking Save, SAB does not accept it, and does not restart. 

I can overrule it by coding a default value instead of None, but both 127.0.0.1 resp 0.0.0.0 as default have consequences. So I would like go back to the earlier value that was filled out

My logging says:
`2022-08-11 18:32:54,263::DEBUG::[cfg:165] SJ: invalid host input`
so the correct code is triggered.

Tips @Safihre  ?

image

**Comment by Safihre** [comment]
Ah, no you can't do that.. The validation system doesn't work like that for any of the values. It just prevent saving bad things and providing feedback why it was blocked. 
If you want the original value back, the user will have to refresh the page.

**Pull request merged**
