### PR TITLE
64-bit version of unrar (for MacOS)

### PR DESCRIPTION
**Pull request by sanderjo**

### CODE REVIEW

**Comment by thezoggy** [comment]
should update the license to reflect the correct version (its still for 5.40).

**Comment by Safihre** [comment]
Which license file? The `license.txt` file in that folder is not version specific as far as I can see.

**Comment by thezoggy** [comment]
what i get for trying to look at git via the phone, yeah ignore me. were good on the license. but anyways do we want to offer 64bit and 32bit utilities like we do on windows so those that want can fall back if there is any issues.. or do we want to just drop all 32bit stuff and do 64bit only?

**Comment by Safihre** [comment]
Since everything else is 64bit (SAB itself and external tools) I think it's safe to go 64bit only.

**Pull request merged**
