### PR TITLE
Test download 10GB

### PR DESCRIPTION
**Pull request by sanderjo**
For people with high speed setups (1+ Gbps) and/or sustained tests

image

### CODE REVIEW

**Comment by Safihre** [comment]
CI tests fail due to taverntesting/tavern/issues/631

**Comment by sanderjo** [comment]
> CI tests fail due to [taverntesting/tavern/issues/631](https://github.com/taverntesting/tavern/issues/631)

that is something I can ignore?

**Comment by Safihre** [comment]
Yes. Just for reference :)

Maybe we should rename 1000MB to 1GB?

**Comment by sanderjo** [comment]
> Maybe we should rename 1000MB to 1GB?

Yup, my idea too. It means we have to change documentation.

image

**Comment by sanderjo** [comment]
1000MB test NZB now also reachable via 1GB

https://github.com/sabnzbd/sabnzbd.github.io/commit/a6b975398458b518c616b6df6a9fb2a69757b051

**Pull request merged**
