### PR TITLE
Do not apply permissions if not requested by the user, but remove xbits

### PR DESCRIPTION
**Pull request by Safihre**
I propose to change the way we handle permissions and no longer force any if the user didn't request them.
With 1 exception: we remove any execution-related bits on files if we find them.
@jcfp What do you think?

If you approve, there is other things that still need to be done:

- [x] Check `os.umask` at start-up to see if it at least allows user read/write on created files.
- [x] Check the Incomplete Directory at startup to see if we have read/write permissions.
- [x] More tests, for example for `removexbits`.
- [ ] Documentation.

### CODE REVIEW

**Comment by sanderjo** [comment]
> I propose to change the way we handle permissions and no longer force any if the user didn't request them.

... which will take care of ACL setups (on DSM7, ad other POSIX systems): if a user wants to use the ACL setup, she/he should not fill out permission settings?


> With 1 exception: we remove any execution-related bits if we find them.

Sounds OK, but why? Becasue of security ... ? 
Please note:
* directories have x-bits. AFAIK they are needed to access and read that directory. Google hit: "A directory with its x bit set allows the user to cd (change directory) into this directory, and access the files in it. The ability to read the names of files stored in this directory. The ability to rename files in the directory, create new files, or delete existing files, if you also have Execute permissions."
* all my files on my exFAT drive have -rwxrwxrwx . Nothing SAB can do about that. However, trying to remove the x bit does not result in an error or a problem

**Comment by Safihre** [comment]
> Sounds OK, but why? Becasue of security ... ? Please note:
> 
> * directories have x-bits. AFAIK they are needed to access and read that directory. Google hit: "A directory with its x bit set allows the user to cd (change directory) into this directory, and access the files in it. The ability to read the names of files stored in this directory. The ability to rename files in the directory, create new files, or delete existing files, if you also have Execute permissions."
> * all my files on my exFAT drive have -rwxrwxrwx . Nothing SAB can do about that. However, trying to remove the x bit does not result in an error or a problem

Should have been more clear: only removes x-bits on _files_.

**Comment by Safihre** [comment]
@jcfp what do you think about the changes?

**Comment by jcfp** [comment]
> @jcfp what do you think about the changes?

I'll comment tomorrow, time permitting.

**Review by jcfp — COMMENTED** [review]
I ignored the possibility that users would set something weird for the permissions (for which they'd receive a warning anyways), particularly anything that has a value of zero when converted to int. That kind of setting could throw off certain checks though, with int(zero) evaluating to False in statements checking if custom permissions have been set.

**Review by jcfp — APPROVED** [review]

**Pull request merged**
