### PR TITLE
SABNews: Fake newsserver for our tests

### PR DESCRIPTION
**Pull request by Safihre**
Last year I started adding functional tests that would emulate user-behavior using Selenium.
Unfortunately, these tests turned out to be unreliable because they depended on the build-systems (Travis/AppVeyor) to have a stable connection to the external newsserver. It was also slow, because we could only run 1 job at a time.

Introducing: SABNews! 
A fake newsserver that we can use for unit-tests. I had to re-implement the `encode` function in `sabyenc` (removed long ago when porting the original [`_yenc` module](https://bitbucket.org/dual75/yenc)) so it was fast enough. 
We can now add more "real" test-downloads easily by adding them to the `tests/data` folder. Using the `add_test_nzb` in `test_functional_downloads` will automatically generate the NZB that can be used with SABNews.

Maybe you guys can take a quick look at the code and see what you think? Comments are appreciated, also for example if parts of the code are unclear! @sabnzbd/contributers

### CODE REVIEW

**Comment by sanderjo** [comment]
I tried to run it, but got the errors below. So `AttributeError: module 'sabyenc3' has no attribute 'encode'` ... do I have to install / remove something?

```
$ python3 sabnews.py -p 4444
INFO:root:Starting SABNews on 127.0.0.1:4444
INFO:root:Connection from ('127.0.0.1', 47728)
DEBUG:root:Data received: b'ARTICLE <test@home>'
WARNING:root:Can't parse article information
DEBUG:root:Data received: b'QUIT'
DEBUG:root:Closing connection
INFO:root:Connection from ('127.0.0.1', 47734)
INFO:root:Connection from ('127.0.0.1', 47736)
INFO:root:Connection from ('127.0.0.1', 47738)
INFO:root:Connection from ('127.0.0.1', 47740)
INFO:root:Connection from ('127.0.0.1', 47742)
INFO:root:Connection from ('127.0.0.1', 47744)
INFO:root:Connection from ('127.0.0.1', 47746)
DEBUG:root:Data received: b'BODY <file=/home/sander/post_this/50MB.bin|part=1|start=0|size=500000>'
DEBUG:root:Serving b'<file=/home/sander/post_this/50MB.bin|part=1|start=0|size=500000>'
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.NewsServerProtocol object at 0x7f494abef8b0>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
    self._protocol.data_received(data)
  File "sabnews.py", line 66, in data_received
    self.serve_article(parsed_message)
  File "sabnews.py", line 113, in serve_article
    output_string, crc = sabyenc3.encode(inp_buffer)
AttributeError: module 'sabyenc3' has no attribute 'encode'
INFO:root:Connection from ('127.0.0.1', 47748)
DEBUG:root:Data received: b'BODY <file=/home/sander/post_this/50MB.bin|part=2|start=500000|size=500000>'
DEBUG:root:Serving b'<file=/home/sander/post_this/50MB.bin|part=2|start=500000|size=500000>'
ERROR:asyncio:Fatal error: protocol.data_received() call failed.
protocol: <__main__.NewsServerProtocol object at 0x7f494abef9d0>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 860, in _read_ready__data_received
    self._protocol.data_received(data)
  File "sabnews.py", line 66, in data_received
    self.serve_article(parsed_message)
  File "sabnews.py", line 113, in serve_article
    output_string, crc = sabyenc3.encode(inp_buffer)
AttributeError: module 'sabyenc3' has no attribute 'encode'
DEBUG:root:Data received: b'BODY <file=/home/sander/post_this/50MB.bin|part=3|start=1000000|size=500000>'
```

**Comment by thezoggy** [comment]
so this doesnt do a mock connection with mock or anything, but instead connects to a 'fake' server using normal code which then just serves up the .nzb ?

**Comment by Safihre** [comment]
Yes, for end to end testing. Unit tests, even if we ever managed to extend them far enough, only cover their respective bits instead of the whole user download and post processing flow.

**Comment by jcfp** [comment]
Nice for reliability and reproducibility alone, one doesn't need to look further than the recent build failures on travis because of connections from different ip addresses to like the concept. Also enables running functional tests in environments where credentials cannot be hidden or no external connections can be done at all (Debian build daemons, Ubuntu CI).

In time, controlling both ends could also be helpful for testing handling of various server-side issues.

**Pull request merged**
