### PR TITLE
Added support for systemd power controls

### PR DESCRIPTION
**Pull request by BrendanBall**
added systemd support to powersup.linux_shutdown, linux_hibernate, linux_standby.

### CODE REVIEW

**Comment by Safihre** [comment]
Trusting @sanderjo with this one to test! 
Might not merge straight away, because we just did a Release Candidate for 2.1.0, so this will go in the next release  :+1:

**Comment by thezoggy** [comment]
@sanderjo sickrage has been around for a bit and used by a bunch of people, so i would suspect their scripts are safe to reference off of: https://github.com/SickRage/SickRage/tree/master/runscripts

**Comment by Safihre** [comment]
@thezoggy That's not what this is for. Those are init scripts, this PR is about the power-options of SABnzbd being called from python. To restart/shutdown/etc the whole PC from SABnzbd.

**Comment by thezoggy** [comment]
yeah just saw what it is, saw systemd and asumed

**Pull request merged**
