### PR TITLE
"3" in SABnzbd logo on frontpage

### PR DESCRIPTION
**Pull request by sanderjo**
as discussed https://github.com/sabnzbd/sabnzbd/issues/1319

We can always improve later on, but I need it now in testing.

### CODE REVIEW

**Comment by thezoggy** [comment]
perhaps the `3` should be done in the same font that 'sab' is in?
I believe it is `FFFFREED.TTF` if you want me to share it

**Comment by sanderjo** [comment]
Oh, the text "SAB" is a _font_ ? I thought a patient person had drawn something.

Anyway ... as you seem to be the expert on this, maybe quicker if you do it, including PR?

**Comment by thezoggy** [comment]
I can, but @Safihre / @inpheaux  actually messed with it the most and may be able to get to this before I can: https://github.com/sabnzbd/sabnzbd/issues/521

**Comment by jeffgeorge** [comment]
For reference: https://www.dafont.com/fff-freedom.font

Not sure what license the font is available under, but it's freely available from dafont.

**Pull request merged**
