### PR TITLE
ssdp: make the time.sleep() less blocking

### PR DESCRIPTION
**Pull request by sanderjo**
Solves https://forums.sabnzbd.org/viewtopic.php?f=11&t=25148

### CODE REVIEW

**Comment by Safihre** [comment]
I think it's better and easier to just use `.kill()` instead of `.join()` in the shutdown. There is no vital information in this thread anyway.

**Comment by sanderjo** [comment]
> I think it's better and easier to just use `.kill()` instead of `.join()` in the shutdown. There is no vital information in this thread anyway.

`.kill()`? Is that a Thread call? I can't find it

```
>>> from threading import Thread
>>> dir(Thread)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_bootstrap', '_bootstrap_inner', '_delete', '_initialized', '_reset_internal_locks', '_set_ident', '_set_native_id', '_set_tstate_lock', '_stop', '_wait_for_tstate_lock', 'daemon', 'getName', 'ident', 'isAlive', 'isDaemon', 'is_alive', 'join', 'name', 'native_id', 'run', 'setDaemon', 'setName', 'start']
>>> 
```

and

```
  File "/home/sander/git/sjo-sab/sabnzbd/utils/ssdp.py", line 159, in stop_ssdp
    __SSDP.kill()
AttributeError: 'SSDP' object has no attribute 'kill'
```

**Comment by sanderjo** [comment]
Just no .join() solves it.

**Comment by Safihre** [comment]
Not using `join` could result in leftover threads after shutdown.
I fixed this problem in 30e692cefeed6a5b5c4c54bc9fa7f934ea0f9133 using `Condition(Lock())`. No `sleep`'s needed :)

**Pull request closed without merging**
