### PR TITLE
Fixed missing font files for bootstrap

### PR DESCRIPTION
**Pull request by Fish2**
Fixed 404 error for missing files on 2.3.0 

Files:
glyphicons-halflings-regular.woff
glyphicons-halflings-regular.woff2

### CODE REVIEW

**Comment by Safihre** [comment]
Where do they cause 404 errors? All references to these 2 files have been removed long ago.

**Comment by Fish2** [comment]
Its in the bootstrap 2.3.0 css file 
screen shot 2017-10-24 at 6 52 07 pm

**Comment by Safihre** [comment]
No it is not, just inspect the file here on the repo:
https://github.com/sabnzbd/sabnzbd/blob/develop/interfaces/Config/templates/staticcfg/bootstrap/css/bootstrap.min.css
Those files were already removed and integrated inside the `bootstrap.min.css` back in 2015:
https://github.com/sabnzbd/sabnzbd/commit/72b1f31f44964d1018f92b45e654e583834babeb#diff-5a1c23a8b3e9cdbb325e9f126f5d0c39

**Comment by Fish2** [comment]
Thats Really strange as on sab 2.3.0 it safari and chrome i get this bootstrap css i had to reformat to txt to upload it.

[bootstrap.txt](https://github.com/sabnzbd/sabnzbd/files/1412024/bootstrap.txt)

**Comment by Fish2** [comment]
I see that the font is added inline with this line ,url(data:font/woff;

so i don't see why it changes that line in the css to look for a file when it is inside bootstrap css

**Comment by Safihre** [comment]
Maybe clear your cache? 
I just double-checked the CSS file that is the macOS package, and it is the same as here on the repo with inline file.

**Comment by Fish2** [comment]
I have clear my cache and my sab is running in docker but i have tried running it on my mac do you get this error on your end ?

**Comment by Safihre** [comment]
Aaaaah, you use a docker with the PPA?  
The @jcfp PPA replaces the Bootstrap files with a package `libjs-bootstrap`, with this side effect. 
Maybe this can be changed for 2.3.1 @jcfp ?

**Comment by Fish2** [comment]
Ok that makes sense why i have a different bootstrap css file

**Comment by jcfp** [comment]
@Fish2 probably the result of using the packaged libjs-bootstrap but not linking these woff files. Have an example url within the sab web interface to trigger this? Makes it easier for me to check if things are actually fixed.

**Comment by Safihre** [comment]
@jcfp all Config pages. But the file is only loaded if it matches the browser/OS, some like the svg or ttf files better that bootstrap also provides.

**Comment by Fish2** [comment]
@jcfp it seams to be all pages including the log in page

**Comment by jcfp** [comment]
Added links for bootstrap woff/woff2 in Config and Glitter. PPA update is in progress.

**Comment by Fish2** [comment]
I have tested the new docker image and all fixed now

**Pull request closed without merging**
