### PR TITLE
Translation things

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by Safihre** [comment]
@shypike I ran make_mo.py on the develop branch and got some errors about %s mismatches that I saw you already fixed on Launchpad, so think you need to push those updates again

**Comment by shypike** [comment]
@Safihre I know and I will.

**Comment by Safihre** [comment]
@shypike Fixed that delete-while-not-finished thing, can't do that in Glitter anymore!

**Comment by shypike** [comment]
Merged

**Pull request closed without merging**
