### PR TITLE
Fixes for Beta2

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by Safihre** [comment]
Added feedback button on the side of Glitter for beta/alpha versions
It shows a list of ways to contact us. Hopefully we get some more feedback this way.
The button only shows for beta/alpha/Github versions and so I did not add extra translations since these users know what they are getting into when installing beta/alpha/git versions.

**Comment by Safihre** [comment]
Updating the wizard: Make everything more user-friendly and streamlined. Port and and # of connections are now placed under 'Show more'. Clicking SSL will change the port to 563.
Username and option for SSL removed from the wizard, they can be enabled in the Config.

**Comment by shypike** [comment]
Merged

**Comment by Safihre** [comment]
You're missing the last 2 commits!

**Comment by shypike** [comment]
Sorry.
The repos are out of sync now.
Is it possible for you to rebase to that I can catch the last two?

**Comment by Safihre** [comment]
Rebased! Just this afternoon I did a rebase of the KnockoutJS update on one of the old commits, it was hanging on that.

**Comment by thezoggy** [comment]
is there a way to remove/disable that feedback thing in glitter?

**Comment by shypike** [comment]
@Safihre Thank you.

**Comment by Safihre** [comment]
No currently there isn't, I opted instead to only show it to Alpha/Beta/Git users.
Maybe adding a close button and it can stay for all users.

**Pull request merged**
