### PR TITLE
Because of dual IPv4/IPv6 clients, finding the public ipv4 needs special attention

### PR DESCRIPTION
**Pull request by sanderjo**
as discussed here https://github.com/sabnzbd/sabnzbd/issues/498

### CODE REVIEW

**Comment by thezoggy** [comment]
maybe a more elegant solution is just to have the page return a json result with both, then just parse the relevant one. 
```
{
    "ipv4": "8.8.8.8",
    "ipv6": ""
}
```

seems way better than some hack of trying to decipher which is which..

**Comment by jeffgeorge** [comment]
I don't think that'll actually solve the problem @sanderjo is going after, because all I get from Cloudflare is the single environment variable `HTTP_CF_CONNECTING_IP`. It may be IPv4 *or* IPv6. If a user has access to both IPv4 *and* IPv6, I have no idea how it'd determine which protocol it actually connects over. I mean, I can parse it (so could you, by just checking the returned string for a `:`), but it's always going to be one or the other. Sander's problem is figuring out how to *force" a check over IPv4 if the client could connect over either.

Also: Is it asking too much to request that any connections to self-test.sabnzbd.org go over SSL? I *know* somebody is going to inspect these connections. When there's scrutiny I'd like to at least have it going over SSL.

**Comment by thezoggy** [comment]
@inpheaux aww gotcha, thought it was just some php/code that you had that served up the info (aka, you had control)

**Comment by Safihre** [comment]
Tried on my IPv6 VPN and works just as expected :) 
@jeffgeorge All we do is request the IP, something a sniffer/hacker would also know. Why now take the risk of more SSL relate problems when it's nothing that needs encrypting?

**Comment by Safihre** [comment]
Merge this and get the 1.0.0 final release party started? :D

**Comment by shypike** [comment]
@Safihre  Really? I'd rather do an extra RC. I get nervous when too many lines of code changes.
It's easy enough to forget a test case, as happened with RC3

**Comment by Safihre** [comment]
This one only affects status information, not anything essential.

**Pull request merged**
