### PR TITLE
Add HTTPS checkbox to Switches

### PR DESCRIPTION
**Pull request by Safihre**
@sanderjo / @shypike What do you think about the wording? Did not want to add info about minimal requirements etc.

It doesn't work when SSL is not available, right? I added that check.

### CODE REVIEW

**Comment by shypike** [comment]
@Safihre It's more subtle.
We test for presence of PyOpenSSL. Standard Python should contain SSL support, but not at the level that NNTP needs. I think that "out-of-the-box" Python always supports https. Maybe some deranged embedded versions do not, but those are not likely to be 2.7.9+ anyway.
So the SSL test isn't really needed. Besides, it won't hurt if the checkbox is available while https isn't working.

**Comment by Safihre** [comment]
@shypike Removed the check for SSL. Do we really need a check if it's the right Python version?
Can't we just make 2.7.9 the minimum requirement for SABnzbd and we done with it?
Because let's face it: from the [download statistics](https://sabnzbd.org/download-stats), 95+% of our users are on Windows/OSX, and the Linux PPA also has the right version. 
Plus we know that QNAP and SynnoCommunity also offer the latest versions.

**Comment by shypike** [comment]
@Safihre No, we cannot make 2.7.9 a requirement. That would exclude too many embedded systems. We don't see the statistics, because they download third-party packages.

**Comment by shypike** [comment]
BTW: There's no need to suppress the actual option on pre 2.7.9 versions.
The enable/disable code already checks for presence of verification capabilities.

**Comment by Safihre** [comment]
Added the #634 fix, if you're fine with the HTTPS text then this is good to go!

**Pull request merged**
