### PR TITLE
Dont run deobfuscate if dvd or bluray typical directory name

### PR DESCRIPTION
**Pull request by sanderjo**
triggered by suggestion https://github.com/sabnzbd/sabnzbd/issues/2014#issuecomment-1005215227

### CODE REVIEW

**Comment by sanderjo** [comment]
RFC:

should the detection of DVD / Bluray be more strict? So check that there are no other files or directories ... ?

**Comment by Safihre** [comment]
I would approach differently, in `deobfuscate_list` the first thing I would do is just check if any of the paths have the DVD/Blu-Ray parts in them.
Something like this (I didn't run this code yet), using the helper-function `match_str`.
```python
for file in filelist:
   if match_str(file, IGNORED_MOVIE_FOLDERS):
      logging.info("Skipping, blu-ray/dvd")
      return filelist
```

**Comment by sanderjo** [comment]
OK, I'll do, but of course there is a danger, because there is no check if it is directory, within the downloaded part.

```
>>> from sabnzbd.misc import match_str
>>> IGNORED_MOVIE_FOLDERS = ("video_ts", "audio_ts", "bdmv")
>>> match_str("/blabla/Complete/Download1/VIDEO_TS/bla/something.txt", IGNORED_MOVIE_FOLDERS) # good
'video_ts'
>>> match_str("/blabla/Complete/Download1/VIDEO_TStreamer/something.txt", IGNORED_MOVIE_FOLDERS) # bad
'video_ts'
>>> match_str("/my_VIDEO_TS/blabla/Complete/Download1/something.txt", IGNORED_MOVIE_FOLDERS) # bad
'video_ts'
```

**Comment by Safihre** [comment]
What you could do, is specifically search for `os.path.sep + search_term + os.path.sep`.
You'll have to make a local copy of the `IGNORED_MOVIE_FOLDERS`.

**Comment by sanderjo** [comment]
What do we want: logging per skipped file (which needs a bit more code), or just one line with the skipped files (which needs a oneliner to create the clean newfiles).

```
2022-01-09 13:49:15,957::INFO::[postproc:525] Running deobfuscate
2022-01-09 13:49:15,958::DEBUG::[deobfuscate_filenames:188] Skipping /media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla2.xml because of DVD/Bluray indicator
2022-01-09 13:49:15,958::DEBUG::[deobfuscate_filenames:188] Skipping /media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla.xml because of DVD/Bluray indicator
2022-01-09 13:49:15,958::DEBUG::[deobfuscate_filenames:188] Skipping /media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla3.xml because of DVD/Bluray indicator
2022-01-09 13:49:15,958::INFO::[deobfuscate_filenames:193] Skipped DVD/Bluray files: ['/media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla.xml', '/media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla3.xml', '/media/sander/6665-6464/fake dvd 10/VIDEO_TS/blabla2.xml']
```

**Pull request merged**
