### PR TITLE
Show available SSL protocols for a Usenet server.

### PR DESCRIPTION
**Pull request by shypike**
Determine available protocols.
Log information about SSL libraries.

### CODE REVIEW

**Comment by Safihre** [comment]
Can we also add this to the setup-wizard? Noticed there we only have SSL on/off but not which type..

**Comment by shypike** [comment]
@Safihre I wish that I knew that before I wrote it :)
The Wizard should automatically pick the highest one. I'll look into that as well.

**Comment by shypike** [comment]
@Safihre I simplified the Config->Server template code.
The Wizard will work fine now: when no ssl_type is set, then the highest available protocol will be picked.

**Comment by shypike** [comment]
Merged

**Pull request closed without merging**
