### PR TITLE
Print low level Windows status error on assembler IOError

### PR DESCRIPTION
**Pull request by puzzledsab**
As discussed in https://forums.sabnzbd.org/viewtopic.php?f=2&t=25261

There are some other places where it could be added but this seems like the spot that usually gives Errno 13. It would be nice to get some feedback from those who have seen the problem.

### CODE REVIEW

**Comment by Safihre** [comment]
Maybe you can also add it to `renamer`, since it's very often used.

**Comment by puzzledsab** [comment]
Problem with the renamer is that it's used a lot of places but it doesn't catch it's own exceptions. I'm not sure how to add it in a way that doesn't break anything, except for adding it everywhere it's used.

**Comment by Safihre** [comment]
Why not log it in this section?
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/filesystem.py#L945
That way at least it's logged when users report things.

**Comment by Safihre** [comment]
Great!

**Pull request merged**
