### PR TITLE
Test adding nzbs

### PR DESCRIPTION
**Pull request by jcfp**
Fixed:
* category-based values from pre-queue didn't work at all, even if no explicit settings were given at any stage;
* explicit settings upon adding the job weren't given precedence over implicit values for pp, script, prio based on the category set by pre-queue;
* state-setting priorities (paused, dup) always used Normal priority as their fallback, instead of whatever priority (except Force which could override the state immediately after it was set) the job would have had based on its category;

For the tests I went with two separate test functions. The first is a reasonably-sized random sample, since a full run over multiple layers of parametrisation ends up too big for CI; the second deals with known issues using fixed sets of parameters.

To prevent configuration changes in functional tests from interfering with unrelated tests elsewhere, the `run_sabnzbd_sabnews_and_selenium` fixture was split and the scope of the new `run_sabnzbd` set to 'module'; the _sabnews_and_selenium_ part remains session-scoped. In the process, bugs surfaced in `tests/test_utils/{test_cert_gen,test_diskspeed,test_internetspeed}.py`, all of which were assuming the cache dir always exists.

### CODE REVIEW

**Comment by thezoggy** [comment]
can you also add adding nzb that should result in various failure states: empty nzb / malform nzb / valid nzb but file gets removed a second later (simulate flakey hdd)

**Comment by jcfp** [comment]
> can you also add adding nzb that should result in various failure states: empty nzb / malform nzb / valid nzb but file gets removed a second later (simulate flakey hdd)

Testing the handling of nzb metadata was already on the (embedded) todo list; adding empty and malformed nzbs shouldn't be a problem. I guess the semi-broken hdd would result in only part of the file getting read, probably best simulated by cutting a valid nzb in two and feeding one of the pieces to sab?

**Comment by thezoggy** [comment]
The flakey hdd is somewhat of a unknown, since usually sab only really checks at the start and if the file looks like it's fine.. so that first half might yield a partial download? The back half I would think it would fail to be added?

**Comment by jcfp** [comment]
I expect sab won't accept either part, because these aren't correctly formed xml files in their own right.

**Comment by jcfp** [comment]
Also added tests with dupe detection set to pause, which seems to work pretty much as expected: always labels, and pauses the job unless priority is set to Force. The changes should cover everything mentioned in #1703 now.

**Comment by Safihre** [comment]
Great :)

I will wait to merge this after we split off the 3.2.x branch somewhere next week. There's already so much in the 3.2.0 release that I would like to put this in 3.3.0!

**Comment by Safihre** [comment]
Thank you!

**Pull request merged**
