### PR TITLE
Check if Completed Download Folder is on FAT. If so, give a warning

### PR DESCRIPTION
**Pull request by sanderjo**
As discussed here: https://github.com/sabnzbd/sabnzbd/issues/848

### CODE REVIEW

**Comment by Safihre** [comment]
Merged 👍

**Comment by thezoggy** [comment]
could have used win32api GetVolumeInformation
http://docs.activestate.com/activepython/2.4/pywin32/win32api__GetVolumeInformation_meth.html

```
D:\temp>python -c "import win32api;print win32api.GetVolumeInformation('D:\\')"
('storage', 107913418, 255, 65470719, 'NTFS')
D:\temp>python -c "import win32api;print win32api.GetVolumeInformation('E:\\')"
('UUI', 452793712, 255, 6, 'FAT32')
```

**Comment by sanderjo** [comment]
@thezoggy OK, interesting. Does it also work for (I have no Windows at hand, so I can't check myself):

win32api.GetVolumeInformation('E:\\somedir\\')
win32api.GetVolumeInformation(''\\\\?\\C:\\Media\\'')

Because 1) we have the full path and 2) it could be the format '\\?\C:\Media\...' ... So we can't be sure the first character is the drive letter. :-(

**Comment by Safihre** [comment]
@sanderjo 
It needs to only be the disk-letter and it's fine with the extra `\\?\`:
```
>>> win32api.GetVolumeInformation('\\\\?\\E:\\')
('Files', -1531830029, 255, 65470719, 'NTFS')
```
But luckily python has a function for that:
```
>>> os.path.splitdrive('\\\\?\\E:\\Downloads\\')
('\\\\?\\E:', '\\Downloads\\')
```

Doesn't work for sub-folders (the `Downloads` definitely exists!):
```
>>> win32api.GetVolumeInformation('E:\\Downloads\\')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (144, 'GetVolumeInformation', 'The directory is not a subdirectory of the root directory.')
```

It also works for mapped network drives:
```
>>> win32api.GetVolumeInformation('Z:\\')
('PromisePegasus', 0, 255, 262278, 'NTFS')
```

But not for network-paths:
```
>>> win32api.GetVolumeInformation('\\\\192.168.37.22\\')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pywintypes.error: (161, 'GetVolumeInformation', 'The specified path is invalid.')
```

**Comment by Safihre** [comment]
It's also really fast:
```
>>> a=time.time(); win32api.GetVolumeInformation('\\\\?\\E:\\'); print 1000*(time.time()-a)
('Files', -1531830029, 255, 65470719, 'NTFS')
3.99994850159
```
Compared to the ~400ms of the current method 👍

**Comment by thezoggy** [comment]
1 loop, 1 run, see it constantly get said info in ~3 msec

```C:\>python -m timeit -n1 -r1 "import win32api;print win32api.GetVolumeInformation('C:\\')"
('', 807141970, 255, 65470719, 'NTFS')
1 loops, best of 1: 2.65 msec per loop```

**Comment by sanderjo** [comment]
@thezoggy If you want, can you create & send a PR? 

(I haven't got a Windows PC with admin rights nor win32api nor a sab-from-source environment)

**Comment by thezoggy** [comment]
note that this code falsely warns about exFAT, which does not have the 4GB file size limit...
`File size limit of 16 EiB − 1 byte`

```
C:\Program Files (x86)\sabnzbd_git\sabnzbd\utils>python checkdir.py E:\
E:\ is on FAT
```

```
C:\>python -c "import win32api;print win32api.GetVolumeInformation('E:\\')"
('ps4', 346629577, 255, 6, 'exFAT')
```

so yes we deff need to update the code and optimize

**Comment by thezoggy** [comment]
could do it in one line..
`FAT = win32api.GetVolumeInformation(os.path.splitdrive(drive)[0])[4].startswith("FAT")`
but having it cleanup the `\\?\` requires an additional line.. then added some debug lines and comment..

**Comment by Safihre** [comment]
@thezoggy You don't need to remove the `\\?\`, see my post above!

**Comment by thezoggy** [comment]
depending on the passed dir.. I had to at certain times (lack of trailing slash)..

```
C:\>python -c "import win32api;print win32api.GetVolumeInformation('\\?\E:')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
pywintypes.error: (123, 'GetVolumeInformation', 'The filename, directory name, or volume label syntax is incorrect.')

C:\>python -c "import win32api;print win32api.GetVolumeInformation('\\\\?\\E:\\')"
('ps4', 346629577, 255, 6, 'exFAT')
```

**Comment by thezoggy** [comment]
looks like we only check the completed folder..  why not the incomplete folder as well?
`2017-03-17 08:56:37,959::INFO::[postproc:174] Completed Download Folder C:\test\downloads\complete is not on FAT`

**Comment by sanderjo** [comment]
@thezoggy would this help to get from both Windows path notations to a drive letter:

`path.replace('\\','').replace('?','')[:2]`

Check:

```
>>> path = '\\\\?\\E:\\and\\more\\bla\\'
>>> path.replace('\\','').replace('?','')[:2]
'E:'
```

```
>>> path = 'E:\\and\\more\\bla\\'
>>> path.replace('\\','').replace('?','')[:2]
'E:'
```

So works for both cases.

**Comment by sanderjo** [comment]
> looks like we only check the completed folder.. why not the incomplete folder as well?

Because in **Incomplete** you will get typical file sizes of a 50 or 100 MB max. So well below the 4GB limit.

Our approach:
- first introduce and release this check for Complete
- if not problems: introduce it for Category destination folders.

**Comment by sanderjo** [comment]
Triggered by @thezoggy 's remark about exFAT, I verified for Linux, and nothing extra is needed in checkdir.py for exFAT on Linux:

Proof:
```
sander@Streamer13:~/git/sab-sanderjo-16maart2017$ python sabnzbd/utils/checkdir.py /media/sander/mijnExFat/somedir/
/media/sander/mijnExFat/somedir/ is not on FAT
```
Reason:
```
/dev/mmcblk1p1 on /media/sander/mijnExFat type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
```
exFAT is mounted via fuse, so the filesystem is fuseblk. No "FAT" in that filesystem.

So ... everything is fine.

**Comment by sanderjo** [comment]
Hmmm, new Ubuntu (20.04) installed, which has Linux kernel 5.4, and suddenly SAB says
```
Completed Download Folder /media/sander/6665-6464/complete is on FAT file system, limiting maximum file size to 4GB
```
... for the same SD card has been not given that warning on Ubuntu 19.04.
Let's see:
```
$ df -T /media/sander/6665-6464/
Filesystem     Type  1K-blocks     Used Available Use% Mounted on
/dev/sdc1      exfat 124835840 82152448  42683392  66% /media/sander/6665-6464
```
Ouch, pure `exfat` and not mounted via fuse anymore.
I'll have to update my code. PR on it's way.

**Comment by sanderjo** [comment]
Windows was already OK:

```
c:\Users\sande\git\sjo-sab-RSS-fix>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sabnzbd.utils.checkdir import isFAT
>>> isFAT("/home/sander/")
False
>>> isFAT("c:\\")
False
>>> isFAT("D:\\")
False
```

Checking internals:

```
>>> import win32api
>>> win32api.GetVolumeInformation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: GetVolumeInformation() takes exactly 1 argument (0 given)
>>> win32api.GetVolumeInformation("D:\\")
('', 1717920868, 255, 131590, 'exFAT')
>>>
```
and isFAT() checks like this: `if result[4].startswith("FAT"):`, so OK.

**Pull request closed without merging**
