### PR TITLE
Fix category script typeahead alignment

### PR DESCRIPTION
**Pull request by thezoggy**
Fix https://github.com/sabnzbd/sabnzbd/issues/2144#issuecomment-1094367933

### CODE REVIEW

**Comment by thezoggy** [comment]
all pytest failed, unrelated to this change

**Comment by Safihre** [comment]
You branched from `3.5.x`? Can you change it to develop? I think that's even possible from Github

**Comment by Safihre** [comment]
Oke I tried and that doesn't work. Could you reopen a PR but based on develop?

**Comment by thezoggy** [comment]
sure i can submit another pr for that branch as well

**Pull request closed without merging**
