### PR TITLE
Handling archives with multiple NZBs from API add_url call

### PR DESCRIPTION
**Pull request by paradix**
Please have a look, maybe it can be usable.

### CODE REVIEW

**Comment by shypike** [comment]
Sorry for the late reaction.
Interesting change.
Do you happen to have a an example of an indexer serving multi-NZB files?

**Comment by paradix** [comment]
I used to test it from a irc channel, serving such archives. Are you on irc?

**Comment by shypike** [comment]
No, I'm not.
But I probably can setup some test situation where I can get a ZIP from a website.
I was mostly wondering abouy the use case, so it's practical usefulness.

**Comment by paradix** [comment]
Well for me it works like that:
 - I get a notice with the URL from a bot on irc 
 - I catch it and send it to sabnzbd
 - if sabsnzbd is online it handles the archive download and the NZBs inside
 - if it's offline I save the archive locally, and upload it later once sabnzbd become available

That's pretty much my use case.

**Comment by shypike** [comment]
Thank you.

**Comment by thezoggy** [comment]
several indexers allow you to check off multiple items in the table, click download.. it serves up a zip of nzb's...  can easily see why someone would just want to load this up (especially if shared to another person for them to load).

**Pull request merged**
