### PR TITLE
sab 0.8.x -- dev pep8 pt5

### PR DESCRIPTION
**Pull request by thezoggy**
More pep8 cleanup, (revert) unused variables by import / duplicate imports / misspelling / some minor renames to avoid using built-in names (list/set/id/etc). Will cleanup addID in another pull.

### CODE REVIEW

**Comment by Safihre** [comment]
Do we really need all those ```@UndefinedVariable``` in the code, just for validation purposes?

**Comment by thezoggy** [comment]
When you code with is specific commands it is. As the coder ide is only going to be able import/validate one is..  Then you have some funky imports that are done because python bugs or for py2exe. Now I can global ignore them but it can hide things that could be better addressed with code portability or wrappers/APIs. 

-----Original Message-----

**Comment by thezoggy** [comment]
if @shypike wants I can set my ide to ignore `undefined variable from import` and cleanup those entries.

**Comment by thezoggy** [comment]
alright, removed the suppression of undefined variables from import comments. forced pushed

**Comment by shypike** [comment]
@thezoggy Thanks for removing the overload of overrides.

**Comment by shypike** [comment]
Merged

**Pull request closed without merging**
